# Youtube Music Playlist API Notebook

In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path: sys.path.append(module_path)

from ytmusic_library import YTMusicPlaylists

RUN_API_AUTH_TEST = True
HEADER_FILE = '../browser.json'
PLAYLIST_TSV_DIR = '../playlists/'

In [2]:
Y = YTMusicPlaylists(header=HEADER_FILE, playlist_tsv_dir=PLAYLIST_TSV_DIR)
if RUN_API_AUTH_TEST: Y.test_ytmusic_api()
print(f"Loaded {len(Y.playlists['title'].unique())} playlists")

Using header file: ../browser.json
-> Method: Browser Authentication (cookies). Skipping OAuth client init.
Test Passed in 2.28 seconds
Using ytmusicapi version: 1.11.1
Loaded 504 playlists

# Clean Up Radio Playlists

* Move LIKE to radios like playlist
* Remove DISLIKE and NOT LIKE

In [3]:
playlist_names = [
# 'Indie Folk radio', 
# 'xr Exotica radio',
# 'xr nudisco radio',
# 'folk acoustic radio', 
# 'xr neopsychedelia radio',
# 'xr indierock radio',
# 'xr chillwave radio', 
# 'electronic Underjord radio',
# 'electronic Focus radio',
'electronic post dub radio',
# "Reggae radio",
# "xr indie radio",
# "xr IndieFolk radio",
# "xr shoegaze radio",
# "xr chillmusic radio", # liminel
# 'xr treemusic radio',
# 'rock surf radio',
# 'reggae classic radio',
# 'nudisco radio',
# 'xr Elephant6 radio',
# 'future beats radio',
# 'xr desertblues radio'
# 'indie krill vibe radio'

]
MIN_RADIO_LIKE_TO_SPLIT=2
for playlist_name in playlist_names:
    assert 'radio' in playlist_name
    pl_info = Y.playlist_get_info(Y.query_by_title(playlist_name).playlistId)
    clean_counters = Y.clean_up_radio_playlist(pl_info, 
        move_like=True, create_like_playlist=True, remove_dislike=True, remove_not_like=True,
        min_num_like=MIN_RADIO_LIKE_TO_SPLIT,  sleep=1, verbose=True,
    )

Playlist electronic post dub radio counters: {'moved_like': 2}

# Re-Sort Playlist based on LastFM playcount 

creates new sorted pl, deletes old

In [8]:
playlist_names = [
  # 'electronic New Wave old and new radio',
  # 'Reggae radio',
  # 'helvetia duster static cult'
  # 'electronic New Wave old and new radio',
  # 'folk acoustic radio',
  'xr Elephant6 radio',
    # 'xr treemusic radio' #'jazz fusion cross radio', 'soul groove instrumental radio', 'jazz funk cortex vibe radio'
]
USE_CACHE=False
for playlist_name in playlist_names:
    pl_info = Y.playlist_get_info(Y.query_by_title(playlist_name).playlistId, use_cache=False)
    pc_df = Y.playcount_sort_playlist(pl_info, ignore_banned=True)

Loaded 469207 playounts from 176023 tracks
Created sorted pl: xr Elephant6 radio [01-17-2026] PLWptjpDqazOyCkLsGcBRaF_2BXLgNbZdB, and  deleted original pl: PLWptjpDqazOyddeiqM76mQJPMC57rRPH9

## Save playlist backup tsv

In [ ]:
PLAYLIST_NAME = 'zz not like 0' # Liked Music
USE_CACHE = False
_pl_id = Y.query_by_title(PLAYLIST_NAME).playlistId
_pl_tracks, _pl_metadata = Y.save_playlist_tsv(Y.playlist_get_info(_pl_id, use_cache=USE_CACHE))

                                                                  0
owned                                                          True
id                               PLWptjpDqazOyCkLsGcBRaF_2BXLgNbZdB
privacy                                                     PRIVATE
description       generated sorting by lastfm playcount for xr E...
views                                                          None
duration                                                   5+ hours
trackCount                                                      268
title                                            xr Elephant6 radio
author            {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
year                                                           2026
related                                                          []
duration_seconds                                              55414

## Update _not_like tsv

In [37]:
not_like_tracks = Y.collect_all_not_like_tracks_from_tsvs()
not_like_tracks.to_csv(Y.not_like_tsv, sep='\t', header=True)
print(f'Saved {len(not_like_tracks)} entries to not_like tsv: {Y.not_like_tsv}')

Found 4 not like playlists out of the 531 total
Updated not liked tracks, contains 10121 entries.
Saved 10121 entries to not_like tsv: ../playlists/_not_liked_tracks.tsv

## Update _like tsv and print like coverage

In [ ]:
like_tracks = Y.collect_all_like_tracks_from_tsvs()
like_tracks.to_csv(Y.like_tsv, sep='\t', header=True)
print(f'Saved {len(like_tracks)} entries to like tsv: {Y.like_tsv}')
# run 1-2026, Found 260 like playlists out of the 527 total

Found 260 like playlists out of the 527 total
Beats Lofi.tsv	92.2% currently liked (of 141 total tracks)
Bossa Nova.tsv	88.0% currently liked (of 25 total tracks)
Brass n chill.tsv	93.0% currently liked (of 258 total tracks)
Chillwave.tsv	97.0% currently liked (of 367 total tracks)
Folk.tsv	95.5% currently liked (of 441 total tracks)
Grunge.tsv	99.0% currently liked (of 103 total tracks)
Hip Hop 1980s.tsv	96.0% currently liked (of 25 total tracks)
Hip Hop 1990s east coast.tsv	100.0% currently liked (of 29 total tracks)
Hip Hop 1990s west Coast.tsv	100.0% currently liked (of 74 total tracks)
Hip Hop 1990s.tsv	96.4% currently liked (of 801 total tracks)
Hip Hop 2000s southern.tsv	84.0% currently liked (of 25 total tracks)
Hip Hop 2000s.tsv	96.7% currently liked (of 92 total tracks)
Hip Hop Hits.tsv	97.2% currently liked (of 250 total tracks)
Indie 1990s Rock.tsv	98.7% currently liked (of 76 total tracks)
Indie 2000s.tsv	97.9% currently liked (of 233 total tracks)
Indie psych.tsv	94.4% currently liked (of 251 total tracks)
Instrumental Acoustic Guitar Explorations.tsv	98.2% currently liked (of 56 total tracks)
Instrumentals Acoustic.tsv	96.8% currently liked (of 31 total tracks)
Japanese City Pop 70s 80s.tsv	100.0% currently liked (of 11 total tracks)
Jazz Guitar.tsv	93.8% currently liked (of 96 total tracks)
Oldies.tsv	93.4% currently liked (of 1160 total tracks)
Post-Punk 1970s-1980s.tsv	97.6% currently liked (of 167 total tracks)
Psychedelic 1960s Orchestra.tsv	100.0% currently liked (of 17 total tracks)
Reggae Dub.tsv	86.9% currently liked (of 221 total tracks)
Reggae.tsv	93.6% currently liked (of 528 total tracks)
Rock 1967-1969.tsv	98.0% currently liked (of 197 total tracks)
Rock 1970s progressive.tsv	92.7% currently liked (of 41 total tracks)
Rock 1980s Pop New Wave.tsv	99.1% currently liked (of 329 total tracks)
Rock Sand Dunes & Guitars.tsv	87.1% currently liked (of 31 total tracks)
Shoegaze.tsv	93.5% currently liked (of 368 total tracks)
Soul Classic Sunshine.tsv	100.0% currently liked (of 94 total tracks)
ambiant electro.tsv	100.0% currently liked (of 65 total tracks)
ambient BOC.tsv	100.0% currently liked (of 41 total tracks)
ambient Dream Pop Deep Sleep.tsv	89.4% currently liked (of 47 total tracks)
ambient Indie synths.tsv	94.0% currently liked (of 84 total tracks)
ambient grouper.tsv	98.6% currently liked (of 72 total tracks)
ambient haunting harmonious.tsv	93.5% currently liked (of 139 total tracks)
ambient japan.tsv	100.0% currently liked (of 50 total tracks)
ambient modern.tsv	99.0% currently liked (of 102 total tracks)
ambient modular synths.tsv	97.2% currently liked (of 36 total tracks)
ambient.tsv	97.8% currently liked (of 950 total tracks)
beats 2010s wonky LA scene.tsv	94.3% currently liked (of 419 total tracks)
beats Soulful Instrumentals.tsv	89.2% currently liked (of 213 total tracks)
beats cosmic Slop.tsv	91.4% currently liked (of 35 total tracks)
beats dj.tsv	89.4% currently liked (of 161 total tracks)
beats instrumental.tsv	88.5% currently liked (of 408 total tracks)
beats.tsv	91.8% currently liked (of 1296 total tracks)
blues chicago.tsv	95.0% currently liked (of 40 total tracks)
blues deep roots.tsv	91.0% currently liked (of 100 total tracks)
blues delta roots.tsv	95.5% currently liked (of 112 total tracks)
blues electric.tsv	92.7% currently liked (of 82 total tracks)
blues texas roots.tsv	96.0% currently liked (of 25 total tracks)
blues.tsv	94.3% currently liked (of 840 total tracks)
brass beats.tsv	87.6% currently liked (of 210 total tracks)
chill solar mix.tsv	98.0% currently liked (of 98 total tracks)
electronic 1990s electronica.tsv	95.9% currently liked (of 49 total tracks)
electronic 1990s late 1980s House.tsv	100.0% currently liked (of 17 total tracks)
electronic 2000s.tsv	95.7% currently liked (of 115 total tracks)
electronic 2010s.tsv	96.0% currently liked (of 50 total tracks)
electronic Analog Grooves.tsv	93.1% currently liked (of 101 total tracks)
electronic Dance.tsv	96.1% currently liked (of 128 total tracks)
electronic Focus.tsv	99.5% currently liked (of 201 total tracks)
electronic Garage Bass House.tsv	96.8% currently liked (of 94 total tracks)
electronic House Soulful.tsv	90.0% currently liked (of 20 total tracks)
electronic House Special.tsv	90.2% currently liked (of 183 total tracks)
electronic Innerwaves.tsv	96.0% currently liked (of 125 total tracks)
electronic New Wave old and new.tsv	97.4% currently liked (of 116 total tracks)
electronic Sine Language.tsv	94.4% currently liked (of 752 total tracks)
electronic Underjord.tsv	93.5% currently liked (of 278 total tracks)
electronic big beats.tsv	100.0% currently liked (of 18 total tracks)
electronic chill.tsv	94.9% currently liked (of 468 total tracks)
electronic chills adventure.tsv	94.6% currently liked (of 185 total tracks)
electronic deep house.tsv	91.4% currently liked (of 162 total tracks)

WARNING: Low Like Percentage!
electronic dubstep uk.tsv	77.8% currently liked (of 54 total tracks)
electronic hard dj.tsv	92.6% currently liked (of 27 total tracks)
electronic house big bass.tsv	88.6% currently liked (of 44 total tracks)
electronic house dj.tsv	93.3% currently liked (of 90 total tracks)
electronic house french touch.tsv	93.7% currently liked (of 95 total tracks)
electronic house funk.tsv	98.0% currently liked (of 50 total tracks)
electronic house.tsv	85.0% currently liked (of 20 total tracks)
electronic indie essentials.tsv	98.5% currently liked (of 67 total tracks)
electronic jaar.tsv	90.2% currently liked (of 41 total tracks)
electronic new indie beats.tsv	95.0% currently liked (of 459 total tracks)
electronic post dub.tsv	90.7% currently liked (of 151 total tracks)
electronic soft pad.tsv	93.7% currently liked (of 79 total tracks)
electronic uk.tsv	93.9% currently liked (of 277 total tracks)
electronic witch house.tsv	91.0% currently liked (of 67 total tracks)
electronic.tsv	93.5% currently liked (of 1422 total tracks)
folk 1960s.tsv	100.0% currently liked (of 99 total tracks)
folk country americana.tsv	92.9% currently liked (of 225 total tracks)
folk fall indie chill.tsv	91.7% currently liked (of 338 total tracks)
future bass.tsv	93.0% currently liked (of 256 total tracks)
future beats.tsv	99.0% currently liked (of 100 total tracks)
future garage.tsv	96.1% currently liked (of 204 total tracks)
garage rock.tsv	94.1% currently liked (of 405 total tracks)
goth 1980s.tsv	100.0% currently liked (of 15 total tracks)
hawaiian steel guitar.tsv	95.0% currently liked (of 20 total tracks)
helvetia duster static cult.tsv	100.0% currently liked (of 125 total tracks)
hiphop Soulquarians.tsv	100.0% currently liked (of 43 total tracks)
hiphop futurebeats.tsv	98.2% currently liked (of 56 total tracks)
hiphop indie.tsv	90.3% currently liked (of 31 total tracks)
hiphop jazzy.tsv	95.2% currently liked (of 271 total tracks)
hiphop modern.tsv	93.5% currently liked (of 536 total tracks)
hiphop old school.tsv	96.4% currently liked (of 1130 total tracks)
hiphop soul good vibe.tsv	92.8% currently liked (of 208 total tracks)
hiphop trap rap dj.tsv	97.6% currently liked (of 41 total tracks)
hiphop wrist twistin.tsv	98.1% currently liked (of 53 total tracks)
hiphop.tsv	95.8% currently liked (of 2382 total tracks)
indie folk.tsv	95.9% currently liked (of 318 total tracks)
indie krill vibe.tsv	96.0% currently liked (of 100 total tracks)
indie loose.tsv	92.5% currently liked (of 1742 total tracks)
indie sleeze.tsv	100.0% currently liked (of 46 total tracks)
indie.tsv	99.1% currently liked (of 1176 total tracks)
jazz ballads.tsv	92.1% currently liked (of 89 total tracks)
jazz blue note latin.tsv	100.0% currently liked (of 44 total tracks)
jazz blue note.tsv	100.0% currently liked (of 58 total tracks)
jazz cool.tsv	92.9% currently liked (of 368 total tracks)
jazz funk cortex vibe.tsv	94.1% currently liked (of 286 total tracks)
jazz fusion cross.tsv	98.3% currently liked (of 118 total tracks)
jazz gloom smooth.tsv	90.7% currently liked (of 150 total tracks)
jazz gypsy.tsv	89.2% currently liked (of 111 total tracks)
jazz japanese.tsv	95.7% currently liked (of 23 total tracks)
jazz noir.tsv	94.5% currently liked (of 471 total tracks)
jazz spiritual.tsv	100.0% currently liked (of 31 total tracks)
jazz sunrise.tsv	98.3% currently liked (of 59 total tracks)
jazz.tsv	93.7% currently liked (of 1336 total tracks)
my balls your chill.tsv	95.4% currently liked (of 329 total tracks)
nudisco smooth.tsv	95.7% currently liked (of 46 total tracks)
nudisco.tsv	93.7% currently liked (of 684 total tracks)
oldies 1930-40s naptime.tsv	100.0% currently liked (of 29 total tracks)
oldies 1950s.tsv	87.4% currently liked (of 222 total tracks)
oldies 1960s.tsv	93.3% currently liked (of 180 total tracks)
oldies doo wop.tsv	88.0% currently liked (of 83 total tracks)
oldies fallout 40s.tsv	95.5% currently liked (of 67 total tracks)
post rock slow core.tsv	85.7% currently liked (of 70 total tracks)
psych ish rock modern.tsv	96.2% currently liked (of 212 total tracks)
psych rock modern.tsv	93.7% currently liked (of 861 total tracks)
psychedelic classic rock.tsv	92.9% currently liked (of 701 total tracks)
punk 1970s.tsv	92.1% currently liked (of 38 total tracks)
reggae classic.tsv	93.4% currently liked (of 212 total tracks)
reggae covers.tsv	94.7% currently liked (of 38 total tracks)
reggae modern.tsv	100.0% currently liked (of 32 total tracks)
rock 1950s roots.tsv	91.5% currently liked (of 342 total tracks)
rock 1960s baroque.tsv	93.3% currently liked (of 15 total tracks)
rock 1960s classic.tsv	96.7% currently liked (of 922 total tracks)
rock 1967 Monterey Pop Festival.tsv	100.0% currently liked (of 42 total tracks)
rock 1967.tsv	98.5% currently liked (of 67 total tracks)
rock 1969 Woodstock.tsv	100.0% currently liked (of 38 total tracks)
rock 1970s classic.tsv	97.1% currently liked (of 1078 total tracks)
rock 1970s pop singer songwriters.tsv	100.0% currently liked (of 64 total tracks)
rock 1980s college on air.tsv	90.9% currently liked (of 55 total tracks)
rock 1990s alternative.tsv	98.4% currently liked (of 252 total tracks)
rock 1990s.tsv	97.3% currently liked (of 525 total tracks)
rock 2000s.tsv	99.2% currently liked (of 124 total tracks)
rock 60s70s.tsv	96.4% currently liked (of 56 total tracks)
rock Deep Cut Kick Back.tsv	96.4% currently liked (of 55 total tracks)
rock Motorik.tsv	93.8% currently liked (of 48 total tracks)
rock blues.tsv	98.8% currently liked (of 85 total tracks)
rock classic.tsv	96.8% currently liked (of 1164 total tracks)
rock garage.tsv	95.0% currently liked (of 516 total tracks)
rock instrumentals classic vintage.tsv	98.2% currently liked (of 109 total tracks)
rock krautrock.tsv	97.7% currently liked (of 259 total tracks)
rock modern chill.tsv	96.0% currently liked (of 667 total tracks)
rock proto metal.tsv	96.6% currently liked (of 29 total tracks)
rock stoner sludge dank.tsv	92.9% currently liked (of 70 total tracks)
rock surf japanese takeshi teraichi.tsv	100.0% currently liked (of 41 total tracks)
rock surf modern.tsv	98.2% currently liked (of 56 total tracks)
rock surf.tsv	94.9% currently liked (of 99 total tracks)
rock underground.tsv	95.7% currently liked (of 23 total tracks)
rockabilly.tsv	91.4% currently liked (of 81 total tracks)
soul 1960s.tsv	98.1% currently liked (of 158 total tracks)
soul funk.tsv	96.0% currently liked (of 1166 total tracks)
soul instrumental grooves.tsv	95.7% currently liked (of 92 total tracks)
soul kings and queens.tsv	96.8% currently liked (of 31 total tracks)
soul motown.tsv	97.9% currently liked (of 141 total tracks)
soul rnb dj.tsv	97.6% currently liked (of 42 total tracks)
soul rock covers.tsv	88.0% currently liked (of 25 total tracks)
summertime covers.tsv	95.5% currently liked (of 22 total tracks)
synth trip.tsv	100.0% currently liked (of 43 total tracks)
trip hop & Ambien®.tsv	92.7% currently liked (of 220 total tracks)
trip hop.tsv	93.1% currently liked (of 405 total tracks)
triphop bristol sound.tsv	94.8% currently liked (of 77 total tracks)
xr 2000smusic.tsv	98.6% currently liked (of 215 total tracks)
xr 2010smusic.tsv	95.1% currently liked (of 122 total tracks)
xr 50sMusic.tsv	89.6% currently liked (of 606 total tracks)
xr 60sMusic.tsv	96.9% currently liked (of 733 total tracks)
xr 70sMusic.tsv	91.3% currently liked (of 912 total tracks)
xr 80sHipHop.tsv	100.0% currently liked (of 31 total tracks)
xr 80sMusic.tsv	97.2% currently liked (of 178 total tracks)
xr 90sMusic.tsv	98.6% currently liked (of 221 total tracks)
xr 90sPunk.tsv	93.3% currently liked (of 30 total tracks)
xr 90sRock.tsv	96.1% currently liked (of 284 total tracks)
xr DreamPop.tsv	94.5% currently liked (of 201 total tracks)
xr Elephant6.tsv	98.5% currently liked (of 134 total tracks)
xr Exotica.tsv	97.3% currently liked (of 111 total tracks)
xr HeadNodders.tsv	100.0% currently liked (of 28 total tracks)
xr MelancholyMusic.tsv	97.7% currently liked (of 43 total tracks)
xr ModernRockMusic.tsv	100.0% currently liked (of 23 total tracks)
xr OldElectronicMusic.tsv	100.0% currently liked (of 106 total tracks)
xr OutlawCountry.tsv	98.1% currently liked (of 106 total tracks)
xr PsychedelicRock.tsv	91.8% currently liked (of 1141 total tracks)
xr PunkRock.tsv	100.0% currently liked (of 38 total tracks)
xr Rock.tsv	97.5% currently liked (of 318 total tracks)
xr RootsMusic.tsv	96.6% currently liked (of 87 total tracks)
xr SoundsVintage.tsv	89.4% currently liked (of 265 total tracks)
xr SurfPunk.tsv	87.5% currently liked (of 24 total tracks)
xr VintageObscura.tsv	92.8% currently liked (of 249 total tracks)
xr acidhouse.tsv	95.2% currently liked (of 21 total tracks)
xr altcountry.tsv	96.2% currently liked (of 52 total tracks)
xr bassheavy.tsv	90.5% currently liked (of 42 total tracks)
xr bluegrass.tsv	97.2% currently liked (of 109 total tracks)
xr bluesrock.tsv	98.6% currently liked (of 211 total tracks)
xr chillmusic.tsv	94.3% currently liked (of 701 total tracks)
xr chillwave.tsv	95.2% currently liked (of 373 total tracks)
xr dancepunk.tsv	96.9% currently liked (of 32 total tracks)
xr deepcuts.tsv	92.1% currently liked (of 139 total tracks)
xr disco.tsv	100.0% currently liked (of 77 total tracks)
xr futurefunkairlines.tsv	92.9% currently liked (of 425 total tracks)
xr futuresynth.tsv	97.1% currently liked (of 35 total tracks)
xr house.tsv	89.2% currently liked (of 130 total tracks)
xr minimal.tsv	97.7% currently liked (of 43 total tracks)
xr monsterfuzz.tsv	100.0% currently liked (of 38 total tracks)
xr neopsychedelia.tsv	91.3% currently liked (of 138 total tracks)

WARNING: Low Like Percentage!
xr realdubstep.tsv	77.4% currently liked (of 62 total tracks)
xr synthrock.tsv	92.3% currently liked (of 26 total tracks)
xr theOverload.tsv	95.7% currently liked (of 92 total tracks)
xr trapmuzik.tsv	96.2% currently liked (of 183 total tracks)
xr treemusic.tsv	94.0% currently liked (of 1843 total tracks)
y 1930s top.tsv	98.8% currently liked (of 81 total tracks)
y 1940s top.tsv	100.0% currently liked (of 32 total tracks)
y 1950s top.tsv	92.2% currently liked (of 334 total tracks)
y 1960s early top.tsv	95.8% currently liked (of 518 total tracks)
y 1960s late top.tsv	97.3% currently liked (of 1481 total tracks)
y 1970s early top.tsv	98.4% currently liked (of 1375 total tracks)
y 1970s late top.tsv	98.1% currently liked (of 987 total tracks)
y 1980s early top.tsv	98.8% currently liked (of 585 total tracks)
y 1980s late top.tsv	96.1% currently liked (of 410 total tracks)
y 1990s early top.tsv	96.5% currently liked (of 1017 total tracks)
y 1990s late top.tsv	96.7% currently liked (of 1286 total tracks)
y 2000s early top.tsv	93.8% currently liked (of 1563 total tracks)
y 2000s late top.tsv	95.3% currently liked (of 2034 total tracks)
y 2010 top.tsv	97.9% currently liked (of 815 total tracks)
y 2010s early top.tsv	96.2% currently liked (of 4199 total tracks)
y 2010s late top.tsv	96.8% currently liked (of 4030 total tracks)
y 2011 top.tsv	95.2% currently liked (of 942 total tracks)
y 2012 top.tsv	96.3% currently liked (of 650 total tracks)
y 2013 top.tsv	95.7% currently liked (of 1125 total tracks)
y 2014 top.tsv	95.3% currently liked (of 1078 total tracks)
y 2015 top.tsv	96.0% currently liked (of 1051 total tracks)
y 2016 top.tsv	97.6% currently liked (of 997 total tracks)
y 2017 top.tsv	96.7% currently liked (of 759 total tracks)
y 2018 top.tsv	95.0% currently liked (of 1577 total tracks)
y 2019 top.tsv	97.7% currently liked (of 617 total tracks)
y 2020 top.tsv	99.1% currently liked (of 531 total tracks)
y 2020s early top.tsv	99.2% currently liked (of 1417 total tracks)
y 2021 top.tsv	99.4% currently liked (of 179 total tracks)
y 2022 top.tsv	97.2% currently liked (of 461 total tracks)
y 2023 top.tsv	96.4% currently liked (of 357 total tracks)
y 2024 top.tsv	95.8% currently liked (of 118 total tracks)
zq dj thumbs up.tsv	89.4% currently liked (of 339 total tracks)
Updated liked tracks with 0 new entries (from 38329 to 38329).
Saved 38329 entries to like tsv: ../playlists/_liked_tracks.tsv

## Get Public Playlists

In [4]:
skip_if_contains = (' radio', 'ym ', ' albums', 'zz not', 'zzz ', 'yyz ', 'Episodes for ', 'Liked Music', 'Podcast Queue')
df_public = Y.get_playlists_by_privacy(privacy='PUBLIC', skip_if_contains=skip_if_contains)
print(f'\nFound {len(df_public)} public playlists')
df_public[['title', 'views', 'trackCount', 'duration']].head(30)

# update function run 2-2026, 270 public playlists
# run 1-2026, 270 public playlists
# run 8-2025, 267 public playlists
# run 1-2025, 270 public playlists, fine descriptions

Found public: 'electronic post dub', Stats: 185 tracks, 6 views, 14+ hours, Description: favorites... | [PLWptjpDqazOxmeskGJ9l3z5pMhMP39TNx]
Found public: 'Reggae', Stats: 530 tracks, 7 views, 35+ hours, Description: None... | [PLWptjpDqazOy1OO5b_SLn4r5Rx3XxemYo]
Found public: 'good', Stats: 85 tracks, 37 views, 20+ hours, Description: None... | [PLDLIpMUUSUXETeVoqYD4YcNKUBHc1g6lA]
Found public: 'xr RootsMusic', Stats: 92 tracks, None views, 5 hours, 53 minutes, Description: favorites compiled from reddit sub r/Roo... | [PLWptjpDqazOzLoVTY4_ghLS-LXZGY4TEE]
Found public: 'blues', Stats: 879 tracks, 2 views, 56+ hours, Description: None... | [PLWptjpDqazOywwzZn-tkczbidWrMVG8_o]
Found public: 'xr acidhouse', Stats: 31 tracks, None views, 3 hours, 1 minute, Description: favorites compiled from reddit sub r/aci... | [PLWptjpDqazOxMwX0OKw8q1P9qp5GOXOhQ]
Found public: 'xr Rock', Stats: 322 tracks, 7 views, 26+ hours, Description: favorites compiled from reddit sub r/Roc... | [PLWptjpDqazOwNTc9f3s_J5m0T68-g5eVl]
Found public: 'post rock slow core', Stats: 74 tracks, 7 views, 9 hours, 41 minutes, Description: generated from Take It Slow includes LIK... | [PLWptjpDqazOzOk6eB8LZft0Lrim8rcqg7]
Found public: 'electronic', Stats: 1433 tracks, None views, 106+ hours, Description: None... | [PLWptjpDqazOwemYgzaTfMieoEZPa8KIvN]
Found public: 'jazz guitar', Stats: 165 tracks, None views, 12+ hours, Description: generated from jazz solo guitar radio in... | [PLWptjpDqazOyi67QCmRGE7vWDua6ZGGeQ]
Found public: 'xr 60sMusic', Stats: 750 tracks, 249 views, 46+ hours, Description: favorites compiled from reddit sub r/60s... | [PLWptjpDqazOzTAvihnt0PZpLX-bj0JJh2]
Found public: 'les rallizes all last ones', Stats: 7 tracks, 9 views, 2 hours, 27 minutes, Description: Last last one... | [PLWptjpDqazOxdFjQJSoaR5SzmKPAuZlvs]
Found public: 'xr VintageObscura', Stats: 258 tracks, 20 views, 18+ hours, Description: favorites compiled from reddit sub r/Vin... | [PLWptjpDqazOxCRv-BI5cEXMTtT8wm21KG]
Found public: 'xr Elephant6', Stats: 134 tracks, None views, 7+ hours, Description: favorites compiled from reddit sub r/Ele... | [PLWptjpDqazOyL3pzna7RXkF5mvWXudVJL]
Found public: 'rock surf', Stats: 99 tracks, 8 views, 4 hours, 22 minutes, Description: Favorite tracks from rock surf radio [12... | [PLWptjpDqazOyWQKNxtahzBz6wpovaPU9S]
Found public: 'xr PsychedelicRock', Stats: 1142 tracks, None views, 100+ hours, Description: favorites compiled from reddit sub r/Psy... | [PLWptjpDqazOz9b2Ge7-PNSYxcGGtBa03X]
Found public: 'xr OutlawCountry', Stats: 106 tracks, 2 views, 6+ hours, Description: favorites compiled from reddit sub r/Out... | [PLWptjpDqazOyuagMuSDaPHqWMQN9eMwzw]
Found public: 'ambient', Stats: 950 tracks, 11 views, 81+ hours, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOwWbU2NWZVGHllM-zoc9Mmy]
Found public: 'rock 1970s classic', Stats: 1079 tracks, 575 views, 69+ hours, Description: Dedupe [08-11-2024] generated from rock ... | [PLWptjpDqazOzUfaj7nFStEH0GtT1Bd5_Q]
Found public: 'Hip Hop 1990s west Coast', Stats: 74 tracks, None views, 5 hours, 13 minutes, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOzG267WQ9NiRrLjvaRAq1Zj]
Found public: 'hiphop', Stats: 2382 tracks, None views, 151+ hours, Description: None... | [PLWptjpDqazOxRTU_GJBmz7cicEKdLuISX]
Found public: 'future beats', Stats: 1350 tracks, None views, 89+ hours, Description: Favorite tracks from future beats 2 radi... | [PLWptjpDqazOzGd-Mg61nE0VYG8xmWDkRe]
Found public: 'rock krautrock', Stats: 259 tracks, 1 views, 30+ hours, Description: generated from krautrock includes LIKE s... | [PLWptjpDqazOzX3Vl0sTRvYdRhwWKo2L4Z]
Found public: 'xr chillwave', Stats: 373 tracks, None views, 24+ hours, Description: favorites compiled from reddit sub r/chi... | [PLWptjpDqazOxbNvaT6XpFErXsFQZ4JCF6]
Found public: 'trip hop', Stats: 406 tracks, None views, 30+ hours, Description: Dedupe [07-07-2024] generated from trip ... | [PLWptjpDqazOxzC2520-Dwn3Ug-r5UpaGp]
Found public: 'xr treemusic', Stats: 1843 tracks, None views, 146+ hours, Description: favorites compiled from reddit sub r/tre... | [PLWptjpDqazOxNxw-kc2eJ1Tt6BFmLwYVH]
Found public: 'xr SoundsVintage', Stats: 265 tracks, 32 views, 17+ hours, Description: favorites compiled from reddit sub r/Sou... | [PLWptjpDqazOzg-qvO-vEu8cxa6YXXv9fG]
Found public: 'xr neopsychedelia', Stats: 138 tracks, None views, 10+ hours, Description: favorites compiled from reddit sub r/neo... | [PLWptjpDqazOyxdOl0KLC1p3rGuQUuI6fv]
Found public: 'indie', Stats: 1176 tracks, None views, 78+ hours, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOzPbRAeZPDeMIS0s8Zh0phK]
Found public: 'electronic idm', Stats: 141 tracks, None views, 13+ hours, Description: favorites compiled from reddit sub r/idm... | [PLWptjpDqazOxPsX3sISNYc91Yezhwb107]
Found public: 'jazz gypsy', Stats: 111 tracks, 21 views, 6+ hours, Description: generated from x_r.GypsyJazz_tracks_radi... | [PLWptjpDqazOyTqRfttR3nwCZBz05ayJSU]
Found public: 'rock garage', Stats: 516 tracks, None views, 28+ hours, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOzpaPg4RVIlY-jia-yBQBdI]
Found public: 'jazz', Stats: 1337 tracks, 1 views, 119+ hours, Description: Dedupe [05-08-2024] None... | [PLWptjpDqazOzLqvCA9cCkPUWjrE1-w-Kp]
Found public: 'jazz noir', Stats: 471 tracks, 23 views, 43+ hours, Description: generated from Jazz Noir includes LIKE s... | [PLWptjpDqazOzXgez9315UJUUmAE_FZ2mO]
Found public: 'xr chillmusic', Stats: 702 tracks, None views, 49+ hours, Description: favorites compiled from reddit sub r/chi... | [PLWptjpDqazOw_tv3IeZpMs7pSG-E7-dDF]
Found public: 'xr 70sMusic', Stats: 912 tracks, 50 views, 72+ hours, Description: favorites compiled from reddit sub r/70s... | [PLWptjpDqazOwvRUMSFs8Dd7X9AkXVvp7Y]
Found public: 'Post-Punk 1970s-1980s', Stats: 167 tracks, None views, 11+ hours, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOxFl2uLHXoMidZAqgnUaAAA]
Found public: 'reggae classic', Stats: 212 tracks, 177 views, 12+ hours, Description: None... | [PLWptjpDqazOxX-tPqOCdiZ28JpscCKgoV]
Found public: 'nudisco', Stats: 684 tracks, 1 views, 48+ hours, Description: None... | [PLWptjpDqazOztogl3p1eqA_V22hNh-krR]
Found public: 'electronic jaar', Stats: 41 tracks, None views, 1 hour, 57 minutes, Description: None... | [PLWptjpDqazOx811f6V-BHTQ0TfKC2qaRG]
Found public: 'rock classic', Stats: 1164 tracks, 2 views, 82+ hours, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOz7LNhVuP_kJlPQl39zA_Qk]
Found public: 'jazz blue note', Stats: 58 tracks, 11 views, 6 hours, 31 minutes, Description: None... | [PLWptjpDqazOwGlZQ-NkB5wLclobDlMLtK]
Found public: 'reggae covers', Stats: 38 tracks, 23 views, 2 hours, 8 minutes, Description: covers... | [PLWptjpDqazOwXZbzT6DMm8Znu22BiUj4N]
Found public: 'Shoegaze', Stats: 368 tracks, None views, 27+ hours, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOx0rD-T35zZyEBsmnOGlWZu]
Found public: 'indie folk', Stats: 318 tracks, 9 views, 21+ hours, Description: None... | [PLWptjpDqazOzUx53oyA5Z7HEPhf3tH8Us]
Found public: 'rock stoner sludge dank', Stats: 70 tracks, None views, 9 hours, 29 minutes, Description: generated from rock stoner sludge dank r... | [PLWptjpDqazOxWXSCwg4cJyEy3HmM_0kSa]
Found public: 'xr house', Stats: 130 tracks, None views, 13+ hours, Description: favorites compiled from reddit sub r/hou... | [PLWptjpDqazOxyqxyHQhfEbBteK6EEEsvT]
Found public: 'future bass', Stats: 256 tracks, None views, 13+ hours, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOxP6qNE-EbnjbnPEmiG7SVV]
Found public: 'xr bassheavy', Stats: 42 tracks, None views, 2 hours, 51 minutes, Description: favorites compiled from reddit sub r/bas... | [PLWptjpDqazOwNa2uvyTomNHez2XNXYWrE]
Found public: 'electronic 2000s', Stats: 115 tracks, 2 views, 8+ hours, Description: generated from electronic 2000s radio in... | [PLWptjpDqazOyRjHqZlep3pf9TbtP94ecM]
Found public: 'xr PunkRock', Stats: 38 tracks, None views, 2 hours, 7 minutes, Description: favorites compiled from reddit sub r/Pun... | [PLWptjpDqazOyD8EdMeeTWlF2EkssJinl0]
Found public: 'xr 2000smusic', Stats: 215 tracks, None views, 13+ hours, Description: favorites compiled from reddit sub r/200... | [PLWptjpDqazOy7RFKfBT_FQeVxqUU8AVN1]
Found public: 'soul funk', Stats: 1166 tracks, None views, 70+ hours, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOxI6u2h08x7JtFhAC8KUuBC]
Found public: 'rock 1990s', Stats: 525 tracks, 1 views, 36+ hours, Description: None... | [PLWptjpDqazOwyzCVDRfCBZLDWxuVBzYaw]
Found public: 'rock 1990s alternative', Stats: 252 tracks, 3 views, 18+ hours, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOwvTpznKWvdkLBZ7XXG8k32]
Found public: 'future garage', Stats: 204 tracks, 1 views, 17+ hours, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOz3-7tjSYEpkPjtx8ItFstc]
Found public: 'electronic Garage Bass House', Stats: 94 tracks, 5 views, 9 hours, 8 minutes, Description: favorites... | [PLWptjpDqazOxN6FjNX23c-uMyPhyb0NUC]
Found public: 'electronic Focus', Stats: 201 tracks, None views, 17+ hours, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOwLKR-4dwYfNiZxFXMXBAZz]
Found public: 'ambient modern', Stats: 102 tracks, 3 views, 10+ hours, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOzQNt1_ELULQ5o-_S_Bb5st]
Found public: 'Rock 1980s Pop New Wave', Stats: 329 tracks, None views, 23+ hours, Description: generated sorting by lastfm playcount fo... | [PLWptjpDqazOzog1yirwwXPidAuuZA4cal]
Found public: 'Hip Hop 1990s', Stats: 801 tracks, None views, 55+ hours, Description: generated from Essential '90s Hip Hop in... | [PLWptjpDqazOzHJ68aXZjPD7NWQUyz8MSs]
Found public: 'Folk', Stats: 441 tracks, 1 views, 29+ hours, Description: generated from Essential Folk includes L... | [PLWptjpDqazOwLX6Rge-x2VTjGdK5wkjsP]
Found public: 'soul motown', Stats: 141 tracks, None views, 8+ hours, Description: generated from soul motown includes LIKE... | [PLWptjpDqazOztLHiiEFUZuJGmeGxAlVlc]
Found public: 'garage rock', Stats: 405 tracks, None views, 22+ hours, Description: Matched local tsv playlist: garage rock... | [PLWptjpDqazOwqojQ__XYIweYTp-Uu-B5R]
Found public: 'electronic witch house', Stats: 67 tracks, None views, 3 hours, 52 minutes, Description: None... | [PLWptjpDqazOw2eb6yfMo3GR1cthi6o_fV]
Found public: 'xr disco', Stats: 77 tracks, None views, 6 hours, 48 minutes, Description: favorites compiled from reddit sub r/dis... | [PLWptjpDqazOzD0k8DzLvbR3s5dGVAzSoO]
Found public: 'xr deepcuts', Stats: 139 tracks, None views, 10+ hours, Description: favorites compiled from reddit sub r/dee... | [PLWptjpDqazOznA53pIVMHv9rWDerijlgt]
Found public: 'xr dancepunk', Stats: 32 tracks, None views, 2 hours, 31 minutes, Description: favorites compiled from reddit sub r/dan... | [PLWptjpDqazOzGvfDplNzfUaqG18n7NqjD]
Found public: 'xr bluesrock', Stats: 211 tracks, 2 views, 19+ hours, Description: favorites compiled from reddit sub r/blu... | [PLWptjpDqazOyRAC1qj8EyV15i1AtcCRIa]
Found public: 'xr bluegrass', Stats: 109 tracks, None views, 6+ hours, Description: favorites compiled from reddit sub r/blu... | [PLWptjpDqazOzBK51Cor30APg41mvf5CqM]
Found public: 'xr altcountry', Stats: 52 tracks, None views, 3 hours, 30 minutes, Description: favorites compiled from reddit sub r/alt... | [PLWptjpDqazOzPFboSMDGDiilsvT6-BDFH]
Found public: 'xr 90sRock', Stats: 284 tracks, 1 views, 20+ hours, Description: favorites compiled from reddit sub r/90s... | [PLWptjpDqazOxGLrsXrjSkxjLjbXSLOYyo]
Found public: 'xr 50sMusic', Stats: 606 tracks, None views, 28+ hours, Description: favorites compiled from reddit sub r/50s... | [PLWptjpDqazOwCLs4ZOeyb_Lg4IgAGlg2L]
Found public: 'electronic dubstep uk', Stats: 54 tracks, 3 views, 4 hours, 15 minutes, Description: generated from x_r.realdubstep_tracks_ra... | [PLWptjpDqazOyDGuN9AWYu2chDsC9pJzIm]
Found public: 'electronic Underjord', Stats: 278 tracks, None views, 23+ hours, Description: favorites... | [PLWptjpDqazOxwrcVg0IbdOdJouqoRUJ5c]
Found public: 'xr Exotica', Stats: 111 tracks, 6 views, 6+ hours, Description: favorites compiled from reddit sub r/Exo... | [PLWptjpDqazOwfCBiFXVhhw0l3tFOBuiC5]
Found public: 'electronic Innerwaves', Stats: 125 tracks, None views, 9+ hours, Description: generated from Innerwaves includes LIKE ... | [PLWptjpDqazOzpnk1CxelsGh3nRQGRtic5]
Found public: 'electronic chill', Stats: 468 tracks, 2 views, 27+ hours, Description: None... | [PLWptjpDqazOwupmyCvkv0tOR7g7uzQSjv]
Found public: 'ambient drone metal', Stats: 22 tracks, None views, 1 hour, 58 minutes, Description: Favorite tracks from ambient drone metal... | [PLWptjpDqazOy_NcVqwe-GGtDQJT84KMZK]
Found public: 'electronic New Wave old and new', Stats: 116 tracks, None views, 8+ hours, Description: favorites... | [PLWptjpDqazOzOoWyB-rBEEVIDS2TdRzvl]
Found public: 'indie loose', Stats: 1742 tracks, 31 views, 109+ hours, Description: None... | [PLWptjpDqazOygyoaRpT447v7SENKpPNfi]
Found public: 'drunk driving', Stats: 51 tracks, 49 views, 3 hours, 36 minutes, Description: None... | [PLgXr9FU_39uXk0EyOKEfKX_6NMZQs2jdo]
Found public: 'chill solar mix', Stats: 98 tracks, 23 views, 7 hours, 2 minutes, Description: favorites... | [PLWptjpDqazOyR-1aywTWKlo84iXCyeMhj]
Found public: 'helvetia duster static cult', Stats: 125 tracks, 19 views, 7+ hours, Description: None... | [PLWptjpDqazOzjmXkauZjzas3yrbI6iGAq]
Found public: 'Hip Hop Hits', Stats: 250 tracks, 1 views, 17+ hours, Description: generated from All-Time Hip Hop Hits inc... | [PLWptjpDqazOwraNSrjGT4f0ITAgsTLn5B]
Found public: 'hiphop modern', Stats: 536 tracks, None views, 33+ hours, Description: generated from hiphop modern radio inclu... | [PLWptjpDqazOycPR1VtMnnVNU_b9FRZZg1]
Found public: 'electronic Sine Language', Stats: 752 tracks, None views, 60+ hours, Description: favorites... | [PLWptjpDqazOzRhuXgE5MNv8EFkTBEkoYj]
Found public: 'hiphop old school', Stats: 1130 tracks, None views, 77+ hours, Description: generated from hiphop old school include... | [PLWptjpDqazOyQKwrNZvNT6ycszr1AvlXz]
Found public: 'xr 2010smusic', Stats: 122 tracks, None views, 9+ hours, Description: favorites compiled from reddit sub r/201... | [PLWptjpDqazOwWltLPE8IThgPJeElLQIUO]
Found public: 'xr 80sMusic', Stats: 178 tracks, 2 views, 13+ hours, Description: favorites compiled from reddit sub r/80s... | [PLWptjpDqazOzghbwsfgt5t0h2BBaf-RyR]
Found public: 'xr theOverload', Stats: 93 tracks, 6 views, 9+ hours, Description: favorites compiled from reddit sub r/the... | [PLWptjpDqazOyzJuUJSFLdFFYBCNtCzIn0]
Found public: 'xr minimal', Stats: 43 tracks, None views, 5 hours, 7 minutes, Description: favorites compiled from reddit sub r/min... | [PLWptjpDqazOytLIbSTULwLCdADFHtod3X]
Found public: 'xr realdubstep', Stats: 62 tracks, None views, 5 hours, 10 minutes, Description: favorites compiled from reddit sub r/rea... | [PLWptjpDqazOxLvllR3H1_7d3ENvCpv_bz]
Found public: 'blues deep roots', Stats: 268 tracks, 141 views, 14+ hours, Description: llm filter on my shiz, acoustic mostly b... | [PLWptjpDqazOwoIXfyz6-eEhhi2BvlsFbw]
Found public: 'xr futurefunkairlines', Stats: 427 tracks, 4 views, 42+ hours, Description: favorites compiled from reddit sub r/fut... | [PLWptjpDqazOyv6M7A3L4ZuGj02rlbvYVV]
Found public: 'psych rock modern', Stats: 861 tracks, 53 views, 58+ hours, Description: None... | [PLWptjpDqazOymOcHuMrY9i8kdxLUzGxDx]
Found public: 'soul instrumental grooves', Stats: 92 tracks, None views, 6 hours, 47 minutes, Description: favorites... | [PLWptjpDqazOwVu6re8zhaCFAdKlTLhcKl]
Found public: 'jazz funk cortex vibe', Stats: 287 tracks, 85 views, 19+ hours, Description: Created for dumping likes from jazz funk... | [PLWptjpDqazOx-vU9X5wpa0mOaLsf9lCZ2]
Found public: 'Archive Mix', Stats: None tracks, None views, None, Description: A mix of songs you haven’t heard in a wh... | [RDTMAK5uy_mZtXeU08kxXJOUhL0ETdAuZTh1z7aAFAo]
Found public: 'Discover Mix', Stats: None tracks, None views, None, Description: Discover great music, picked just for yo... | [RDTMAK5uy_n_5IN6hzAOwdCnM8D8rzrs3vDl12UcZpA]
Found public: 'Reggae Dub', Stats: 221 tracks, 2 views, 14+ hours, Description: Dedupe [07-07-2024] generated from Regga... | [PLWptjpDqazOz2XweW6Y1li4ZTbJycyDGW]
Found public: 'Bossa Nova', Stats: 25 tracks, None views, 1 hour, 27 minutes, Description: generated from Bossa Nova includes LIKE ... | [PLWptjpDqazOxSvAlRXI-V4t7cW94qZM3E]
Found public: 'xr trapmuzik', Stats: 183 tracks, None views, 10+ hours, Description: favorites compiled from reddit sub r/tra... | [PLWptjpDqazOzdod2_RK5KoTzt1-NFEYca]
Found public: 'hiphop jazzy', Stats: 271 tracks, None views, 18+ hours, Description: None... | [PLWptjpDqazOyfO1n77MvWet0a8h5VY2Z0]
Found public: 'xr futuresynth', Stats: 35 tracks, None views, 2 hours, 43 minutes, Description: favorites compiled from reddit sub r/fut... | [PLWptjpDqazOx3z9jsMzNxLWAoKHuz9B1J]
Found public: 'xr MelancholyMusic', Stats: 43 tracks, None views, 3 hours, 26 minutes, Description: favorites compiled from reddit sub r/Mel... | [PLWptjpDqazOwDJj1xhKgLsNPRiGJaWJBE]
Found public: 'oldies fallout 40s', Stats: 67 tracks, 2 views, 3 hours, 10 minutes, Description: favorites... | [PLWptjpDqazOyga4tX6SYVlUYU3n6d5Vpv]
Found public: 'brass beats', Stats: 210 tracks, None views, 12+ hours, Description: favorites... | [PLWptjpDqazOymUI6DFy39OqbMELRkwRCX]
Found public: 'ambient grouper', Stats: 72 tracks, 71 views, 4 hours, 34 minutes, Description: favorites... | [PLWptjpDqazOz4HXkF9LeVtrls7lQiKrEL]
Found public: 'ambient japan', Stats: 50 tracks, 2 views, 4 hours, 20 minutes, Description: Created for dumping likes from ambient j... | [PLWptjpDqazOyLja3PB-cIjAvYTBIyUcM_]
Found public: 'rockabilly', Stats: 81 tracks, 1 views, 3 hours, 46 minutes, Description: generated from rockabilly radio includes... | [PLWptjpDqazOxew11zNKfaCFVBcr2OY4N_]
Found public: 'rock 60s70s', Stats: 57 tracks, 50 views, 4+ hours, Description: None... | [PLWptjpDqazOx50W0qtyng9O8zhngc5Woh]
Found public: 'Oldies', Stats: 1161 tracks, None views, 59+ hours, Description: Dedupe [05-08-2024] generated from Danci... | [PLWptjpDqazOzPesSNSAxO4ai3uOWgeLRe]
Found public: 'blues electric', Stats: 82 tracks, 7 views, 5 hours, 46 minutes, Description: Created for dumping likes from blues ele... | [PLWptjpDqazOyzUo3Gxa-VW8dQ131bS5x1]
Found public: 'y 2010s late top', Stats: 4033 tracks, None views, 270+ hours, Description: Top MusicBee tracks for 2010s late (upda... | [PLWptjpDqazOxjJ4QUcmtUvzfuKtO0OQz8]
Found public: 'y 2010s early top', Stats: 4540 tracks, None views, 306+ hours, Description: Top MusicBee tracks for 2010s early (upd... | [PLWptjpDqazOzXOCUzwde2LNXexv420cUP]
Found public: 'y 2000s late top', Stats: 2035 tracks, 2 views, 138+ hours, Description: Top MusicBee tracks for 2000s late (upda... | [PLWptjpDqazOz30x1PbrlNXR_W-D1lb1ef]
Found public: 'y 2000s early top', Stats: 1564 tracks, None views, 111+ hours, Description: Top MusicBee tracks for 2000s early (upd... | [PLWptjpDqazOzwkbKwMod9R48YgWBUobg_]
Found public: 'y 1990s late top', Stats: 1286 tracks, None views, 94+ hours, Description: Top MusicBee tracks for 1990s late (upda... | [PLWptjpDqazOw8sBgs1L6_cb_iGfcTFpSX]
Found public: 'y 1990s early top', Stats: 1017 tracks, None views, 76+ hours, Description: Top MusicBee tracks for 1990s early (upd... | [PLWptjpDqazOwrBRdnvnifl0TnHn5kiVWI]
Found public: 'y 1980s late top', Stats: 412 tracks, 2 views, 29+ hours, Description: Top MusicBee tracks for 1980s late (upda... | [PLWptjpDqazOyld8JDj3fIFCzRJxIfvQ4A]
Found public: 'y 1980s early top', Stats: 585 tracks, None views, 41+ hours, Description: Top MusicBee tracks for 1980s early (upd... | [PLWptjpDqazOxZOpg32F6Fnax3y5rD_TYU]
Found public: 'y 1970s late top', Stats: 987 tracks, 1 views, 77+ hours, Description: Top MusicBee tracks for 1970s late (upda... | [PLWptjpDqazOxAEvHf-iqI0wmGeeyBIBEE]

                             title  views  trackCount             duration
155             trip hop & Ambien®    700       220.0            17+ hours
166               indie krill vibe    579       451.0            30+ hours
18              rock 1970s classic    575      1079.0            69+ hours
191             rock 1960s classic    527       923.0            55+ hours
143                 jazz spiritual    256        31.0  3 hours, 29 minutes
10                     xr 60sMusic    249       750.0            46+ hours
222                   hiphop indie    185        31.0    2 hours, 1 minute
37                  reggae classic    177       212.0            12+ hours
225                 Rock 1967-1969    144       197.0            13+ hours
93                blues deep roots    141       268.0            14+ hours
231                      Chillwave    133       367.0            21+ hours
194       Hip Hop 1990s east coast    126        29.0   2 hours, 7 minutes
257                       zp elvis    107        41.0   1 hour, 40 minutes
193                      jazz cool     91       368.0            33+ hours
97           jazz funk cortex vibe     85       287.0            19+ hours
146                     xr 90sPunk     83        30.0   1 hour, 33 minutes
108                ambient grouper     71        72.0  4 hours, 34 minutes
189           jazz blue note latin     64        44.0  5 hours, 43 minutes
172  electronic house french touch     62        96.0             7+ hours
203         Hip Hop 2000s southern     61        25.0   1 hour, 46 minutes
258        rock Deep Cut Kick Back     54        56.0             3+ hours
195     beats 2010s wonky LA scene     53       420.0            18+ hours
95               psych rock modern     53       861.0            58+ hours
253   ambient Dream Pop Deep Sleep     53        47.0  3 hours, 10 minutes
260      electronic Analog Grooves     51       101.0             6+ hours
35                     xr 70sMusic     50       912.0            72+ hours
227             rock 1960s baroque     50        15.0           55 minutes
111                    rock 60s70s     50        57.0             4+ hours
246              blues texas roots     50        25.0   1 hour, 14 minutes
81                   drunk driving     49        51.0  3 hours, 36 minutes

## Get Playlist Counts

## Get radio playlists with lots of likes

In [5]:
%%time
playlist_file = os.path.join(PLAYLIST_TSV_DIR, '_playlist_radio_counts.tsv')
playlists = Y.get_playlist_counts(verbose=False, filter_title='radio')
playlists.to_csv(playlist_file, sep='\t', index=False)
# Note: now part of ytmusic backup

playlists.head(20)
# last run 2-2026

Getting playlist track count for playlists (takes ~5 minutes)
Only for playlists with radio in the title
CPU times: total: 34.8 s
Wall time: 4min 25s

,title,track_count,privacy,playlist_id
0,indie krill vibe radio,22,PRIVATE,PLWptjpDqazOy10kXns-iHXWsxBRQyb_Si
78,xr Samplehunters radio,23,PRIVATE,PLWptjpDqazOwxUqgcJItuO9jNl3Jcg_fL
73,xr foreignrap radio,25,PRIVATE,PLWptjpDqazOzjYZVOFq_e_A3nlSdFe8vI
92,xr dubtechno radio,25,PRIVATE,PLWptjpDqazOxlekzaH0s1kBmoDYwfd_to
88,xr gamemusic radio,27,PRIVATE,PLWptjpDqazOyYqtWSh1_cyv_IDFvs8KS7
129,xr chillmusic radio,29,PRIVATE,PLWptjpDqazOxNK0_Dt9ijVP9RJZMM_Gd9
85,xr icm radio,30,PRIVATE,PLWptjpDqazOwIeSpwFTzviniXIDxo7tIL
98,xr BinauralMusic radio,31,PRIVATE,PLWptjpDqazOwg0uL9JgZpUWJK58HlV7_E
19,xr GypsyJazz radio,32,PRIVATE,PLWptjpDqazOx_aDtCHfgLIo0att6y0xCb
89,xr frisson radio,43,PRIVATE,PLWptjpDqazOzZWeXU9wroauyqrzaP5Os4
96,xr choralmusic radio,44,PRIVATE,PLWptjpDqazOzHJTYUkpPkF3WMX0n-8sj7
94,xr darkjazz radio,47,PRIVATE,PLWptjpDqazOwswjQ8WLlW2a5LXTzkZPZ4
77,xr soca radio,49,PRIVATE,PLWptjpDqazOzEa1OnXz5rfEisTfaqyBTJ
103,folk acoustic radio,52,PRIVATE,PLWptjpDqazOxv5a0XEcSdpXpKiERCIHZA
174,jazz for spies radio,53,PRIVATE,PLWptjpDqazOyj2ARv0edtYtxjiscELzT3
82,xr liftingmusic radio,54,PRIVATE,PLWptjpDqazOwRVPONTkoaD4yp5lYYwwI4
162,christmas crooners radio,56,PRIVATE,PLWptjpDqazOx6WdsiNzxLHnAdh8v1IjTa
13,xr Rock radio,59,PRIVATE,PLWptjpDqazOy8ffw6_k03M17RLsifgV4N
58,xr kpop radio,60,PRIVATE,PLWptjpDqazOweC74ZHMuactSyim1uPrvH
87,xr glitchhop radio,61,PRIVATE,PLWptjpDqazOxVLm2YSC81rbrzdhIfiG0w

# One Off

### Check albums_musicbee_like_from_ytmusic_matches

1. Looks at `albums_musicbee_like_from_ytmusic_matches.m3u` (copied in musicbe in db format saved as `./logs/maybe_like.tsv`)
2. Checks ytmusic to see if actual like
3. Output pasted in gemini can look to see if any bad like matches or misses (not like)
4. Goal is to batch like or not like `albums_musicbee_like_from_ytmusic_matches.m3u`

In [20]:
import pandas as pd
import re
import difflib
import sys
import os
from collections import defaultdict

# ==========================================
# 1. CONFIGURATION
# ==========================================
# Source info: Created 2/2026 using musicbee db copy to tsv logic

INPUT_DIR = './logs/'
OUTPUT_DIR = './logs/'
INPUT_FILE = os.path.join(INPUT_DIR, 'maybe_like.tsv')

M3U_LIKE = os.path.join(OUTPUT_DIR, 'artists_musicbee_IS_LIKE_from_ytmusic_matches.m3u')
M3U_NOT_LIKE = os.path.join(OUTPUT_DIR, 'artists_musicbee_IS_NOT_LIKE_from_ytmusic_matches.m3u')

pd.set_option('display.max_rows', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 50)

# Keywords that MUST match if present in one but not the other
CRITICAL_KEYWORDS = {'demo', 'live', 'instrumental', 'remix', 'acoustic', 'session', 'reprise', 'part'}

# HARDCODED OVERRIDES
# Format: ('normalized_artist', 'normalized_title'): True (Like) / False (Not Like)
MANUAL_OVERRIDES = {
    # User Request: Duke Ellington -> Like
    ('dukeellingtonandhisorchestra', 'diminuendoinblueandcrescendoinblue'): True,
    ('dukeellington', 'diminuendoinblueandcrescendoinblue'): True, # cover both artist variants
    
    # User Request: Durand Jones (Demo) -> Not Like
    ('durandjones', 'dontyouknowdemo'): False,
    ('durandjonesandtheindications', 'dontyouknowdemo'): False,

    # User Request: J Dilla -> Not Like (Fix false ID match)
    ('jdilla', 'wontdo'): False,

    # User Request: Young Marble Giants (Clicktalk) -> Not Like (Fix false positive to "The Clock")
    ('youngmarblegiants', 'clicktalk'): False,
    
    # Previous Fixes
    ('thecosmicjokers', 'galacticsupermarketpart3'): False,
    ('outkast', 'interlude'): False,
}

# ==========================================
# 2. HELPER FUNCTIONS
# ==========================================
def normalize(s):
    """Standardizes string: lowercase, remove musicbee tags, and strip specific noise suffixes."""
    s = str(s).lower()
    s = re.sub(r'\[.*?\]', '', s) 
    
    # NEW: Remove specific long administrative suffixes that confuse fuzzy matchers
    # Example: "Clicktalk (Taken From The Final Day Single)" -> "Clicktalk"
    s = re.sub(r'\(taken from.*?\)', '', s)
    s = re.sub(r'\(single version\)', '', s)
    
    # Keep alphanumeric and spaces
    s = re.sub(r'[^a-z0-9 ]', '', s)
    return s.strip()

def normalize_key(s):
    """Stricter normalization for dictionary keys (no spaces)."""
    return re.sub(r'\W+', '', normalize(s))

def get_keywords(s):
    """Extracts critical version keywords."""
    s = normalize(s)
    found = set()
    for kw in CRITICAL_KEYWORDS:
        if re.search(r'\b' + re.escape(kw) + r'\b', s):
            found.add(kw)
    return found

def check_version_mismatch(in_title, res_title):
    in_kws = get_keywords(in_title)
    res_kws = get_keywords(res_title)
    if in_kws != res_kws:
        return True, f"Version mismatch: {in_kws} vs {res_kws}"
    return False, ""

def get_enhanced_score(s1, s2):
    n1, n2 = normalize(s1), normalize(s2)
    if not n1 or not n2: return 0
    
    base_score = int(difflib.SequenceMatcher(None, n1, n2).ratio() * 100)
    
    # Substring Boost (Only if substantial length)
    if (n1 in n2 or n2 in n1) and len(min(n1, n2, key=len)) > 3:
        return max(base_score, 95)
    return base_score

def save_m3u(filepath, paths):
    clean = [str(p) for p in paths if p and str(p).strip() and str(p).lower() != 'nan']
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write("#EXTM3U\n")
        f.write("# Generated using musicbee db copy to tsv logic (2/2026)\n")
        f.write('\n'.join(clean) + '\n')
    print(f"Saved {filepath} ({len(clean)} tracks)")

# ==========================================
# 3. LOAD DATA
# ==========================================
print("--- LOADING DATA ---")
liked_ids, liked_lookup = set(), defaultdict(list)

# Load Liked DB
if hasattr(Y, 'like_tsv') and os.path.exists(Y.like_tsv):
    try:
        df_db = pd.read_csv(Y.like_tsv, sep='\t')
        id_col = next((c for c in ['videoId', 'id'] if c in df_db.columns), 'Unnamed: 0')
        liked_ids = set(df_db[id_col].dropna().astype(str))
        
        for _, row in df_db[['title', 'artist']].fillna('').iterrows():
            if row['title']: 
                norm_key = normalize_key(row['title'])
                liked_lookup[norm_key].append(row.to_dict())
        print(f"Loaded {len(liked_ids)} Liked IDs.")
    except Exception as e:
        print(f"Error reading Liked DB: {e}")

# Load Input
if os.path.exists(INPUT_FILE):
    df_input = pd.read_csv(INPUT_FILE, sep='\t').fillna('')
    df_input.columns = df_input.columns.str.strip()
    print(f"Loaded {len(df_input)} items.")
else:
    print(f"ERROR: Input file not found.")
    df_input = pd.DataFrame()

# ==========================================
# 4. PROCESSING LOOP
# ==========================================
results, m3u_liked, m3u_not_liked = [], [], []
total = len(df_input)

if total > 0:
    print(f"Processing {total} items...")
    
    for i, row in df_input.iterrows():
        if i % 10 == 0: sys.stdout.write(f"\rProgress: {int((i+1)/total*100)}%"); sys.stdout.flush()

        artist = str(row.get('Artist', '')).strip()
        title = str(row.get('Title', '')).strip()
        album = str(row.get('Album', '')).strip()
        path = str(row.get('Path', '')).strip()
        
        clean_title = re.sub(r'\[.*?\]', '', title).strip()
        query = f"{clean_title} {artist}" if artist else f"{clean_title} {album}"

        # Manual Override Check
        override_key = (normalize_key(artist), normalize_key(clean_title))
        override_val = MANUAL_OVERRIDES.get(override_key)

        matches = []
        for item in Y.yt.search(query, filter='songs')[:5]:
            is_liked, reason = False, ""
            
            # A. ID Check
            if item['videoId'] in liked_ids:
                is_liked, reason = True, "ID Match"
            else:
                # B. Fuzzy DB Check
                res_norm = normalize_key(item['title'])
                cands = liked_lookup.get(res_norm, [])
                if not cands:
                    close_keys = difflib.get_close_matches(res_norm, liked_lookup.keys(), n=1, cutoff=0.85)
                    for k in close_keys: cands.extend(liked_lookup[k])
                
                res_arts = [normalize_key(a['name']) for a in item.get('artists', [])]
                for c in cands:
                    db_art = normalize_key(c['artist'])
                    if any(ra in db_art or db_art in ra for ra in res_arts):
                        is_liked, reason = True, f"Ref: {c['title']}"
                        break
            
            score_t = get_enhanced_score(clean_title, item['title'])
            item_art = " ".join([a['name'] for a in item.get('artists', [])])
            score_a = get_enhanced_score(artist, item_art)
            final_score = int(score_t * 0.7 + score_a * 0.3) if artist else score_t
            
            is_mismatch, mismatch_note = check_version_mismatch(clean_title, item['title'])
            
            # C. ID Sanity Check (New Fix)
            # If ID Matches but Text Score is abysmal (<40), it's likely a bad metadata link or sample ID match
            if is_liked and reason == "ID Match" and score_t < 40:
                  is_mismatch = True
                  mismatch_note = f"Suspicious ID Match (Score {score_t})"

            matches.append({
                'data': item, 'is_liked': is_liked, 'reason': reason,
                'score': final_score, 'title_score': score_t,
                'is_mismatch': is_mismatch, 'mismatch_note': mismatch_note
            })


        # Selection
        matches.sort(key=lambda x: x['score'], reverse=True)
        best = None
        status = "Not Liked"
        notes = ""

        if override_val is not None:
            status = "LIKED" if override_val else "Not Liked"
            notes = f"Manual Override: FORCE {str(override_val).upper()}"
            (m3u_liked if override_val else m3u_not_liked).append(path)
            best = matches[0] if matches else None
        else:
            valid_liked = next((m for m in matches if m['is_liked'] and not m['is_mismatch'] and m['title_score'] > 65), None)
            
            if valid_liked:
                best = valid_liked
                status = "LIKED"
                notes = best['reason']
                m3u_liked.append(path)
            else:
                best = matches[0] if matches else None
                status = "Not Liked"
                m3u_not_liked.append(path)
                if best and best['is_liked']:
                     notes = f"Rejected: {best['mismatch_note']}" if best['is_mismatch'] else f"Rejected: Low Score ({best['title_score']})"
                elif not best: notes = "No Results"
                else: notes = "Closest match not in Liked DB"

        if best:
             results.append({
                'Status': status, 'Score': best['score'], 'TitleScore': best['title_score'],
                'Input Query': query[:35], 'Found Title': best['data']['title'][:35], 'Match Notes': notes
            })
        else:
             results.append({'Status': status, 'Score':0, 'TitleScore':0, 'Input Query': query[:35], 'Found Title': '', 'Match Notes': notes})

    print("\nDone.")
    save_m3u(M3U_LIKE, m3u_liked)
    save_m3u(M3U_NOT_LIKE, m3u_not_liked)

    if results:
        df_out = pd.DataFrame(results).fillna('')
        print("\n" + "="*80 + "\nMATCHING RESULTS\n" + "="*80)
        def sort_helper(row):
            if row['Status'] == 'LIKED': return 0
            if 'Rejected' in str(row['Match Notes']): return 1
            if 'Manual Override' in str(row['Match Notes']): return 0.5
            return 2
        df_out['sort_key'] = df_out.apply(sort_helper, axis=1)
        df_out.sort_values(by=['sort_key', 'Score'], ascending=[True, False], inplace=True)
        print(df_out.drop(columns=['sort_key']).to_string())

--- LOADING DATA ---
Loaded 38329 Liked IDs.
Loaded 4 items.
Processing 4 items...
Progress: 25%
Done.
Saved ./logs/artists_musicbee_IS_LIKE_from_ytmusic_matches.m3u (0 tracks)
Saved ./logs/artists_musicbee_IS_NOT_LIKE_from_ytmusic_matches.m3u (4 tracks)

================================================================================
MATCHING RESULTS
================================================================================
      Status  Score  TitleScore                          Input Query Found Title Match Notes
0  Not Liked      0           0  Her Eyelids Say Félicia Atkinson &               No Results
1  Not Liked      0           0  All Night I Carpenter Félicia Atkin              No Results
2  Not Liked      0           0      Let Him Run Wild The Beach Boys              No Results
3  Not Liked      0           0           The Hard One The Beta Band              No Results

### Blues list

In [ ]:
for title in Y.playlists['title'].unique():
  if "blues" in title.lower():
    print(title)

blues
blues chicago
blues delta roots
blues electric
blues texas roots
rock blues
xr blues radio
xr bluesrock
xr bluesrock albums
xr bluesrock radio

In [ ]:
pl_info = Y.playlist_get_info(Y.query_by_title('blues texas roots').playlistId)
for track in pl_info['tracks']:
  print()
  print(f"Title: {track['title']}\nArtist: "
        f"{track['artists'][0]['name'] if track['artists'] else 'Unknown'}\n" 
        f"Album: {track['album']['name'] if track['album'] else 'Unknown'}\n"
        f"VideoID: xx\n"
  )

Title: Mean Old World
Artist: T-Bone Walker
Album: T-Bone Blues
VideoID: M_ZDGFBKbBM

Title: Groundhog Blues
Artist: Lil' Son Jackson
Album: Blues Come to Texas
VideoID: i0yihJQ27yg

Title: Captain, Captain!
Artist: Mance Lipscomb
Album: Captain, Captain!
VideoID: -Wp_0pAf4hM

Title: Ticket Agent
Artist: Lil' Son Jackson
Album: Blues Come to Texas
VideoID: ZHWTbE2ZN6U

Title: Back to Santa Fe
Artist: Lee Hunter
Album: Texas Blues: Bill Quinn's Gold Star Recordings
VideoID: FccZzqOMh4A

Title: Freddie
Artist: Mance Lipscomb
Album: The Best of Mance Lipscomb
VideoID: 90vatUNRvBk

Title: Strike Blues
Artist: L.C. Williams
Album: Texas Blues: Bill Quinn's Gold Star Recordings
VideoID: zO_5gdnFua0

Title: Bye Bye Baby Blues
Artist: Little Hat Jones
Album: Don't Leave Me Here: The Blues Of Texas, Arkansas & Louisiana (1927-1932)
VideoID: KI4hlzHUvZM

Title: I Don't Want No Woman
Artist: L.C. Lightnin Jr. Williams
Album: The Mercury Blues Story (1945-1955) - Southwest Blues, Vol. 2
VideoID: 3LQj4X-JNtk

Title: Cairo Blues
Artist: Lil' Son Jackson
Album: Blues Come to Texas
VideoID: bw_x1oWG3oQ

Title: God Don't Never Change
Artist: Blind Willie Johnson
Album: The Complete Blind Willie Johnson
VideoID: tZRve-Iehsk

Title: I Don't Like to Travel
Artist: L.C. Lightnin Jr. Williams
Album: The Mercury Blues Story (1945-1955) - Southwest Blues, Vol. 2
VideoID: DRuJTf0Xw9I

Title: Flower Garden Blues
Artist: Arnett Cobb
Album: Arnett Blows for 1300
VideoID: Izy7CwdpTMU

Title: Blues in the Ghetto
Artist: Pee Wee Crayton
Album: Blues in the Ghetto
VideoID: mzP465lAC4U

Title: Louise
Artist: L.C. Lightnin Jr. Williams
Album: The Mercury Blues Story (1945-1955) - Southwest Blues, Vol. 2
VideoID: Vgn6zk4VZEs

Title: Tennessee Blues
Artist: Clarence "Gatemouth" Brown
Album: Timeless
VideoID: Q29FA-UTlpE

Title: Coffee Blues
Artist: Lightnin' Hopkins
Album: Sittin' In With Harlem Jade & Jax, Vol. 2
VideoID: aR8s8DayZDg

Title: Disagreeable
Artist: Lightnin' Hopkins
Album: Lightnin' Hopkins Vol. 1 (1950-1961)
VideoID: Ok-8pDKxrh4

Title: Hound Dog
Artist: Willie Mae Thornton
Album: Rock 'n' Roll & the City
VideoID: Q25PAh-p9lo

Title: Daybreak
Artist: Pee Wee Crayton
Album: Pee Wee's Blues: The Complete Aladdin And Imperial Recordings
VideoID: K1BVwg0v_p4

Title: Freight Train Blues
Artist: Lightnin' Hopkins
Album: The Best Of Lightnin' Hopkins
VideoID: 6xpjCYTRpEg

Title: Dark Was the Night, Cold Was the Ground
Artist: Blind Willie Johnson
Album: The Complete Blind Willie Johnson
VideoID: 71Ti_TdpJHE

Title: Walking Blues
Artist: Big Mama Thornton
Album: Hound Dog / The Peacock Recordings
VideoID: JObMhKnuwV8

Title: Blue Devil Blues
Artist: Texas Alexander
Album: Texas Alexander Vol. 2 (1928-1930)
VideoID: rB0pXI0Fna4

Title: Kind-Hearted Blues
Artist: Andrew Hogg
Album: Family Trouble Blues
VideoID: wx6mj_bsjxU

In [ ]:
track_ids = [
    "dUKcpeVvHsU",
    "FKCwRDB42wo",
    "s5Y8o6PKFnc",
    "6rf8QfII7kg",
    "AzRuGcEcaVo",
    "EOkIazVPwEo",
    "vQClDmtYBys",
    "ac8rL2Ga7pA",
    "PsrFAbFdNWI",
    "jviYDmdLX2A",
    "ayuhW1p_7wo",
    "oYGJVCOklOo",
    "6YFuk97BdPw",
    "xxoO9Da5_Dg",
    "I4ZLZag9GFs",
    "FCvHEXdtPl4",
    "ZG6xibft3pA",
    "1RKlbgvY2gA",
    "r72I3Ps5zYc",
    "UwXA62rDK7U",
    "tMd7qNr5Ct8",
    "Ex0uCvA3tEM",
    "rB0pXI0Fna4",
    "KI4hlzHUvZM",
    "Jl5W8RaG8GM",
    "Uqcu9wZnGL4",
    "_NPUfBpr0RE",
    "2v0yPrdgfRQ",
    "IPcPYsJwJZc",
    # "qS3gCsJ0",
    # "I91a6_-6M",
    "02IkbJkazLs",
    "LfgK9FckrWo",
    "1tE36dBdsP0",
    "Px6unLbNu4Q",
    "05ypnm_Wcls",
    "Wp1hKpIKzNE",
    "CUIF8cGf3ow",
    "aANSKrs87FA",
    "WmJhMFZEzc8",
    "HP8b6B9-wNg",
    "vn28G8yLsw",
    "TjazJ39k1GY",
    "71Ti_TdpJHE",
    "tZRve-Iehsk",
    "qasPCNQuo88",
    "o8l4LTBwoBE",
    "Ftp4TZKGoug",
    "sk4Js6Q58h8",
    "a5zslcqNCKo",
    "RyZm921d1BU",
    "u-FvKRUTIq4",
    "itiEgttbO0M",
    "-b2XeTb7dY4",
    "mhIQYEoLrjU",
    "AIAw2fAFNMA",
    "Ee7Vg3kf0yY",
    "5SyV43rP-xA",
    "rmJRtSGk-lM",
    "Egfcm2ldXU4",
    "h8R3Oy28BKM",
    "APSCifra1eY",
    "_0gCaSaoULw",
    "_rCswNoJnLI",
    "2seZr4Fl4XA",
    "gIHoUxzRoL8",
    "m09tdbsnxKc",
    "nBGloVKAUyU",
    "2jyGShRb9Xc",
    "bJ_7nYEpkBo",
    "O9D4vnBK2EY",
    "TVK4tHUDw4k",
    "Gn9tDgSYxUw",
    "__BF3XGyC2A",
    "p9CDKtc1Cno",
    "QDfw2ZjtWsQ",
    "ZwAhSaZXq8s",
    "Ryl62yEEo0k",
    "SLBl9O1mfVw",
    "EcpwNuNV81g",
    "hRfw5LiO-II",
    "lKAKcyxNMTo",
    "q5ZBRo_PEGI",
    "_Ke_Sx54nqg",
    "0RvYSvkXJTY",
    "p-gma8xBhtc",
    "jRbgQdMwfIg",
    "vV5FIfYNToI",
    "qo0pS6-_7fU",
    "xYlrGYMsEFQ",
    "3fqrf35BSB4",
    "s5l8U0IuCAs",
    "w2-AYZ-0b0Y",
    "hewWQHInYfE",
    "0zXnPyCKTyM",
    "HVHT1Ylw9dI",
    "G2URlDdDTMo",
    "HK-wBlSUim4",
    "-_lpSR4qkKM",
    "DXH-k1TJKp0",
    "OlOC8Nnpu5U",
    "6S1nuD0qzok",
    "kYsQ5YnlS8s",
    "yPK2PlvnRdw",
    "mVVLjQ-JL3I",
    "1lGct_aPS0Y",
    "ep5wEuJGe54",
    "_Rtey8efdN0",
    "8gvT1tkIM1E",
    "VdYVANxDNkg",
    "Rd8az69QAgk",
    "BD7Jnfziauk",
    "cqh9YVmN-bw",
    "0wnzhf7yQow",
    "0ojDQtWzQ9U",
    "xSTNY3MzePc",
    "jKAXzdkg1ZM",
    "2oXtUngpb-k",
    "a-jG19Ew0Ts",
    "W5grmfiq-3E",
    "Dlx5jjqAbwc",
    "FrPCnqotrKU",
    "-5hhnDy6g_M",
    "2gLsxLymOXU",
    "5ceg8qP2mMk",
    "_AaVUj5_n4Y",
    "w_eHuP-ZjBQ",
    "kElKF-o8yAE",
    "u84pv9IoxLs",
    "MujCppywrSY",
    "VyGPF-7cDSQ",
    "A-qSfOZtkS4",
    "Gbj0jOHoZkw",
    "x_TN6_QQ_hs",
    "mwWGkUChlVs",
    "QDJSAKIE478",
    "7jZ1Jvl7iJ0",
    "KuASnGBsYvs",
    # "7vZ0UcW7uc",
    "L_X-ELsy29A",
    "2iMAncZRopU",
    "OFJUhGC4_hg",
    "fy-WDdCOxtg",
    "so8PplCs_4M",
    "8pw_S-z-NtY",
    "EzzouzKQEC8",
    "P_p7G3NinP8",
    "qPTVVS-E0U4",
    "FIUY2mT5jdw",
    "ETV43779Cho",
    "qwt_5QM2Ncg",
    "0it7r8u4YdM",
    "kBjIGGKq8FI",
    "ODGmMu74pLU",
    "C-JzxdsMi44",
    "Yd3_exRntgI",
    # "diXGcBzb9c",
    "crpFPqIhosI",
    "3o1bj2NlTzU",
    "0iogbdYUI2g",
    "hpXXu8W51Q4",
    "5u8NKsmBpQQ",
    "WAL6UaCfMKo",
    "6xpjCYTRpEg",
    "lXx_9mir89k",
    "aR8s8DayZDg",
    "qgoiowZJJFY",
    "T8B1oHV-2Ig",
    "izVOMmRYdgU",
    "Ok-8pDKxrh4",
    "-6Veo7FBgy0",
    "TX6HpnL0fJ4",
    "BCHuUfO3V_M",
    "ZHWTbE2ZN6U",
    "i0yihJQ27yg",
    "cRhk3U9JDRg",
    "bw_x1oWG3oQ",
    "3LQj4X-JNtk",
    "Vgn6zk4VZEs",
    "zO_5gdnFua0",
    "DRuJTf0Xw9I",
    "FccZzqOMh4A",
    "AueZSrRKILQ",
    "JObMhKnuwV8",
    "Jr9q485COk0",
    "Q25PAh-p9lo",
    "TixL6Tycgho",
    "Vg0pAG0olhk",
    "m-g5kQkqTm8",
    "6koa37cPnAQ",
    "rqg767YC6jM",
    "CrFYHAVppk0",
    "tgt1EXbKbF0",
    "DYlOlv9G3S8",
    "nJAfRMEM4BM",
    "wkS0fPu6mgM",
    "hRdDUGjLVyo",
    "vh5iwTwdrrI",
    "3Lwqu84s5KA",
    "5jcGY7NbaQw",
    "pd7b1Ye6Oc0",
    "4JPAmLuGjxc",
    "ndLLu2dKhVY",
    "J21pL6Ixwoc",
    "0cNbufPYaNQ",
    "d0MS6KKneNE",
    "UVsDDlYw-vE",
    "bZ7xtmkZzrA",
    "EDN8Cm8uTEs",
    "If5ZGXKG9bw",
    "CJqwsIo2NIE",
    "oW5hvQmHLdY",
    "6W9PuLcoZMM",
    "EKdOD12qA6w",
    "DI82cMEhGTI",
    "KIhOgN2gze8",
    "1FFg_iaV_I4",
    "bBulJ5GflP4",
    "IELXveTOkD0",
    "sjFWYuqsmc8",
    "rkTAbWmY-Xc",
    "WVpfJFMiAT8",
    "i3sf67o_Z24",
    "-Wp_0pAf4hM",
    "JRN8CsQBbZk",
    "90vatUNRvBk",
    "fx6whTRhSX4",
    "149RjCpglYI",
    "BkTUWwRZOL8",
    "0to4rm6qkCU",
    "GY7yZiIG-Aw",
    "wy3ugz4S2y0",
    "EemQuYyAMfI",
    "hadkU_g-QZ0",
    "JLKRG_5prAQ",
    "EEZFPg0D_to",
    "WN98EMjmhjU",
    "BbCFDd5y8oA",
    "34IZJuaC6MM",
    "H9bbNJT_RsE",
    "qgGldvMvd7Q",
    "HJHXt_upF1c",
    "vdF63_M-Hjw",
    "bbBZfBRn8NI",
    "-tzvaZ3x9tI",
    "DytRYq0MlCg",
    "1t_dmd1jqKw",
    "-zGH3hD13QQ",
    "ZVl_2e1E8w8",
    "PxgSVxKS69k",
    "Rwx2QYCCwvg",
    "XjwWsuSJrb0",
    "TtzIy1YUVXU",
    "wI_5kbOkTy0",
    "5c-qKZ9Okdw",
    "c-YFPWgvqMw",
    "K3WrKG96FVI",
    "hnVnrn4zVF4",
    "cvzAlmU2EtE",
    "FkOoxzgJ6XM",
    "T8tmW4elTW0",
    "fAJNcskK3Zo",
    "Ve7zunCWxfs",
    "LRiDQy_tq38",
    "LQV4cZMnOwU",
    "jql3d6QjF_M",
    "d8ANsVwTc8w",
    "JLD1IYd0fUA",
    "pcLTW6Rfdh4",
    "-KAemIcX90U",
    "5-CJcXfydV0",
    "0Fsrx_cTBLI",
    "rs8EJNXtyy4",
    "AUtDsHqpd_0",
    "sbtTeP95A3o",
    "WijB-yh_mWU",
    "i0yihJQ27yg",
    "-Wp_0pAf4hM",
    "ZHWTbE2ZN6U",
    "FccZzqOMh4A",
    "90vatUNRvBk",
    "zO_5gdnFua0",
    "KI4hlzHUvZM",
    "3LQj4X-JNtk",
    "bw_x1oWG3oQ",
    "tZRve-Iehsk",
    "DRuJTf0Xw9I",
    "Vgn6zk4VZEs",
    "aR8s8DayZDg",
    "Ok-8pDKxrh4",
    "Q25PAh-p9lo",
    "6xpjCYTRpEg",
    "71Ti_TdpJHE",
    "JObMhKnuwV8",
    "rB0pXI0Fna4",
]

keep_ids = set()
for track_id in track_ids:
  print(track_id)
  try:
    res = Y.yt.get_song(track_id)
    if not res['playabilityStatus']['status'] == 'OK':
      print(f"Error: {res['playabilityStatus']['status']}")
      continue
  except Exception as e:
    print(f"Error: {e}")
    continue
  
  keep_ids.add(track_id)

  
  # break

dUKcpeVvHsU
FKCwRDB42wo
s5Y8o6PKFnc
6rf8QfII7kg
AzRuGcEcaVo
EOkIazVPwEo
vQClDmtYBys
Error: UNPLAYABLE
ac8rL2Ga7pA
PsrFAbFdNWI
jviYDmdLX2A
ayuhW1p_7wo
oYGJVCOklOo
6YFuk97BdPw
xxoO9Da5_Dg
I4ZLZag9GFs
FCvHEXdtPl4
ZG6xibft3pA
1RKlbgvY2gA
r72I3Ps5zYc
UwXA62rDK7U
tMd7qNr5Ct8
Ex0uCvA3tEM
rB0pXI0Fna4
KI4hlzHUvZM
Jl5W8RaG8GM
Uqcu9wZnGL4
_NPUfBpr0RE
2v0yPrdgfRQ
IPcPYsJwJZc
02IkbJkazLs
LfgK9FckrWo
1tE36dBdsP0
Px6unLbNu4Q
05ypnm_Wcls
Wp1hKpIKzNE
Error: UNPLAYABLE
CUIF8cGf3ow
aANSKrs87FA
WmJhMFZEzc8
Error: UNPLAYABLE
HP8b6B9-wNg
vn28G8yLsw
Error: ERROR
TjazJ39k1GY
71Ti_TdpJHE
tZRve-Iehsk
qasPCNQuo88
o8l4LTBwoBE
Ftp4TZKGoug
sk4Js6Q58h8
a5zslcqNCKo
RyZm921d1BU
u-FvKRUTIq4
itiEgttbO0M
-b2XeTb7dY4
mhIQYEoLrjU
AIAw2fAFNMA
Ee7Vg3kf0yY
5SyV43rP-xA
rmJRtSGk-lM
Egfcm2ldXU4
h8R3Oy28BKM
APSCifra1eY
_0gCaSaoULw
_rCswNoJnLI
2seZr4Fl4XA
gIHoUxzRoL8
m09tdbsnxKc
nBGloVKAUyU
2jyGShRb9Xc
bJ_7nYEpkBo
O9D4vnBK2EY
TVK4tHUDw4k
Gn9tDgSYxUw
__BF3XGyC2A
p9CDKtc1Cno
QDfw2ZjtWsQ
ZwAhSaZXq8s
Ryl62yEEo0k
SLBl9O1mfVw
EcpwNuNV81g
hRfw5LiO-II
lKAKcyxNMTo
q5ZBRo_PEGI
_Ke_Sx54nqg
0RvYSvkXJTY
p-gma8xBhtc
jRbgQdMwfIg
vV5FIfYNToI
qo0pS6-_7fU
xYlrGYMsEFQ
3fqrf35BSB4
s5l8U0IuCAs
w2-AYZ-0b0Y
hewWQHInYfE
0zXnPyCKTyM
HVHT1Ylw9dI
G2URlDdDTMo
HK-wBlSUim4
-_lpSR4qkKM
DXH-k1TJKp0
OlOC8Nnpu5U
6S1nuD0qzok
kYsQ5YnlS8s
yPK2PlvnRdw
mVVLjQ-JL3I
1lGct_aPS0Y
ep5wEuJGe54
_Rtey8efdN0
8gvT1tkIM1E
VdYVANxDNkg
Rd8az69QAgk
BD7Jnfziauk
cqh9YVmN-bw
0wnzhf7yQow
0ojDQtWzQ9U
xSTNY3MzePc
jKAXzdkg1ZM
2oXtUngpb-k
a-jG19Ew0Ts
W5grmfiq-3E
Dlx5jjqAbwc
FrPCnqotrKU
-5hhnDy6g_M
2gLsxLymOXU
5ceg8qP2mMk
_AaVUj5_n4Y
w_eHuP-ZjBQ
kElKF-o8yAE
u84pv9IoxLs
MujCppywrSY
VyGPF-7cDSQ
A-qSfOZtkS4
Gbj0jOHoZkw
x_TN6_QQ_hs
mwWGkUChlVs
QDJSAKIE478
7jZ1Jvl7iJ0
KuASnGBsYvs
L_X-ELsy29A
2iMAncZRopU
OFJUhGC4_hg
fy-WDdCOxtg
so8PplCs_4M
8pw_S-z-NtY
EzzouzKQEC8
P_p7G3NinP8
qPTVVS-E0U4
FIUY2mT5jdw
ETV43779Cho
qwt_5QM2Ncg
0it7r8u4YdM
kBjIGGKq8FI
ODGmMu74pLU
C-JzxdsMi44
Yd3_exRntgI
crpFPqIhosI
3o1bj2NlTzU
0iogbdYUI2g
hpXXu8W51Q4
5u8NKsmBpQQ
WAL6UaCfMKo
6xpjCYTRpEg
lXx_9mir89k
aR8s8DayZDg
qgoiowZJJFY
T8B1oHV-2Ig
izVOMmRYdgU
Ok-8pDKxrh4
-6Veo7FBgy0
TX6HpnL0fJ4
BCHuUfO3V_M
ZHWTbE2ZN6U
i0yihJQ27yg
cRhk3U9JDRg
bw_x1oWG3oQ
3LQj4X-JNtk
Vgn6zk4VZEs
zO_5gdnFua0
DRuJTf0Xw9I
FccZzqOMh4A
AueZSrRKILQ
JObMhKnuwV8
Jr9q485COk0
Q25PAh-p9lo
TixL6Tycgho
Vg0pAG0olhk
m-g5kQkqTm8
6koa37cPnAQ
rqg767YC6jM
CrFYHAVppk0
tgt1EXbKbF0
DYlOlv9G3S8
nJAfRMEM4BM
wkS0fPu6mgM
hRdDUGjLVyo
vh5iwTwdrrI
3Lwqu84s5KA
5jcGY7NbaQw
pd7b1Ye6Oc0
4JPAmLuGjxc
ndLLu2dKhVY
J21pL6Ixwoc
0cNbufPYaNQ
d0MS6KKneNE
UVsDDlYw-vE
bZ7xtmkZzrA
EDN8Cm8uTEs
If5ZGXKG9bw
CJqwsIo2NIE
oW5hvQmHLdY
6W9PuLcoZMM
EKdOD12qA6w
DI82cMEhGTI
KIhOgN2gze8
1FFg_iaV_I4
bBulJ5GflP4
IELXveTOkD0
sjFWYuqsmc8
rkTAbWmY-Xc
WVpfJFMiAT8
i3sf67o_Z24
-Wp_0pAf4hM
JRN8CsQBbZk
90vatUNRvBk
fx6whTRhSX4
Error: ERROR
149RjCpglYI
BkTUWwRZOL8
0to4rm6qkCU
GY7yZiIG-Aw
wy3ugz4S2y0
EemQuYyAMfI
hadkU_g-QZ0
JLKRG_5prAQ
EEZFPg0D_to
WN98EMjmhjU
BbCFDd5y8oA
34IZJuaC6MM
H9bbNJT_RsE
qgGldvMvd7Q
HJHXt_upF1c
vdF63_M-Hjw
bbBZfBRn8NI
-tzvaZ3x9tI
DytRYq0MlCg
1t_dmd1jqKw
-zGH3hD13QQ
ZVl_2e1E8w8
PxgSVxKS69k
Rwx2QYCCwvg
XjwWsuSJrb0
TtzIy1YUVXU
wI_5kbOkTy0
5c-qKZ9Okdw
c-YFPWgvqMw
K3WrKG96FVI
hnVnrn4zVF4
cvzAlmU2EtE
FkOoxzgJ6XM
T8tmW4elTW0
fAJNcskK3Zo
Ve7zunCWxfs
LRiDQy_tq38
LQV4cZMnOwU
jql3d6QjF_M
d8ANsVwTc8w
JLD1IYd0fUA
pcLTW6Rfdh4
-KAemIcX90U
5-CJcXfydV0
0Fsrx_cTBLI
rs8EJNXtyy4
AUtDsHqpd_0
sbtTeP95A3o
WijB-yh_mWU
i0yihJQ27yg
-Wp_0pAf4hM
ZHWTbE2ZN6U
FccZzqOMh4A
90vatUNRvBk
zO_5gdnFua0
KI4hlzHUvZM
3LQj4X-JNtk
bw_x1oWG3oQ
tZRve-Iehsk
DRuJTf0Xw9I
Vgn6zk4VZEs
aR8s8DayZDg
Ok-8pDKxrh4
Q25PAh-p9lo
6xpjCYTRpEg
71Ti_TdpJHE
JObMhKnuwV8
rB0pXI0Fna4

In [ ]:
print(f"Keep {len(keep_ids)} of {len(track_ids)}")

Keep 267 of 291

In [ ]:
pl_id = Y.yt.create_playlist(
                  title='blues deep rootss', description='llm filter on my shiz',
                  privacy_status='PUBLIC', video_ids=list(keep_ids),
              )

In [ ]:
#blues = Y.playlist_get_info(Y.query_by_title('blues').playlistId)
for track in pl_info['tracks']:
  print(f"Title: {track['title']}\nArtist: "
        f"{track['artists'][0]['name'] if track['artists'] else 'Unknown'}\n" 
        f"Album: {track['album']['name'] if track['album'] else 'Unknown'}\n"
        f"VideoID: {track['videoId']}\n"
  )

Title: Kind-Hearted Blues
Artist: Andrew Hogg
Album: Family Trouble Blues
VideoID: wx6mj_bsjxU

Title: Ain't No Tellin'
Artist: Mississippi John Hurt
Album: American Epic: The Best of Mississippi John Hurt
VideoID: ZG6xibft3pA

Title: I Got a Funny Feeling
Artist: Arthur "Guitar" Kelley
Album: Louisiana Blues
VideoID: 0Fsrx_cTBLI

Title: I'm A Man
Artist: Bo Diddley
Album: Bo Diddley
VideoID: OKlAiuaYdoI

Title: What'd I Say
Artist: Lightnin' Hopkins
Album: The Very Best of Lightnin' Hopkins (Expanded Edition)
VideoID: __BF3XGyC2A

Title: Susie Q
Artist: Sonny Boy Williamson
Album: MOONSHINE
VideoID: uMgskIh2ZV0

Title: Come On In My Kitchen
Artist: Robert Johnson
Album: The Skeleton Key (Original Motion Picture Soundtrack)
VideoID: 2sh483rVV2Y

Title: Cane Break Blues (Instrumental)
Artist: Merle Travis
Album: Walkin' The Strings
VideoID: FXbx1S5sqG0

Title: How Many More Years
Artist: Freddie King
Album: Texas Cannonball
VideoID: zpr0ThSSSOU

Title: Highway 61
Artist: Mississippi Fred McDowell
Album: Mississippi Fred McDowell
VideoID: EKdOD12qA6w

Title: Dirty Pool
Artist: Stevie Ray Vaughan & Double Trouble
Album: Texas Flood (Legacy Edition)
VideoID: gSLZaEFs1Mw

Title: Pile Driving Blues
Artist: Memphis Minnie
Album: Pickin' the Blues
VideoID: Egfcm2ldXU4

Title: When Something Is Wrong with My Baby
Artist: Sam & Dave
Album: Stax Classics
VideoID: Gdc0llIaD8s

Title: Baby Please Don't Go
Artist: Big Joe Williams
Album: Absolutely the Best of the Blues
VideoID: w_eHuP-ZjBQ

Title: The Moon Shines Bright
Artist: John Renbourn
Album: The Black Balloon
VideoID: -4f0P1SY6Fg

Title: My Daily Wish
Artist: Otis Spann
Album: Great Northern Stomp
VideoID: XjwWsuSJrb0

Title: Ain't No Sunshine (Single Version)
Artist: Bill Withers
Album: Lean on Me: The Best of Bill Withers
VideoID: 5PeyzXvvdmw

Title: Waiting Around to Die
Artist: Townes Van Zandt
Album: Townes Van Zandt
VideoID: NqX6FE0xIJg

Title: Damn Right, I've Got the Blues
Artist: Buddy Guy
Album: Damn Right, I've Got The Blues
VideoID: pk9qe5F0mcY

Title: Sloppy Drunk
Artist: Jimmy Rogers
Album: Blues Follow Me All Day Long: The Complete Shelter Recordings Of Jimmy Rogers / Chicago Blues Master
VideoID: pIGOcGaJzSE

Title: Walkin' Blues
Artist: Robert Johnson
Album: Martin Scorsese Presents The Blues: Robert Johnson
VideoID: O9D4vnBK2EY

Title: Lost Without Love
Artist: Lonesome Sundown
Album: I'm A Mojo Man: The Best Of The Excello Singles
VideoID: jql3d6QjF_M

Title: Pickin' The Blues
Artist: Elmore James
Album: Elmore James' The Sky Is Crying
VideoID: ndLLu2dKhVY

Title: Louisiana Blues
Artist: Muddy Waters
Album: The Best Of Muddy Waters
VideoID: 0nf_bjcYRpI

Title: Wang Dang Doodle
Artist: Koko Taylor
Album: Koko Taylor
VideoID: X4xum7FVPh8

Title: Mama Talk To Your Daughter
Artist: J.B. Lenoir
Album: The Blues: Expanded Edition
VideoID: 5c-qKZ9Okdw

Title: Trouble No More
Artist: The Allman Brothers Band
Album: The Allman Brothers Band
VideoID: xtVaehHadmc

Title: Grinnin' in Your Face
Artist: Son House
Album: The Original Delta Blues (Mojo Workin': Blues For The Next Generation)
VideoID: fx67wTRhSX4

Title: I Got A Girl
Artist: Tripping Daisy
Album: I Am An Elastic Firecracker
VideoID: bsirFURZhio

Title: Sister, Do You Know My Name?
Artist: The White Stripes
Album: De Stijl
VideoID: FHfYzbE5Z3k

Title: Sit and Cry (The Blues)
Artist: Buddy Guy
Album: Southern Blues 1957-63
VideoID: Y0GAI1ep_6U

Title: Traveling Riverside Blues (Previously Unissued Alternate Take from Original Session 06-20-1937)
Artist: Robert Johnson
Album: King of the Delta Blues Singers (1961)
VideoID: TVK4tHUDw4k

Title: Get Back
Artist: Al Green
Album: Al Green Is Blues
VideoID: Hl8niNgZMhw

Title: Release Me
Artist: Junior Kimbrough
Album: You Better Run: The Essential Junior Kimbrough
VideoID: RwazxynpCeo

Title: I'm a Man
Artist: Lazy Lester
Album: Smoking Gun: West Coast Blues
VideoID: LRiDQy_tq38

Title: Dust My Broom
Artist: Elmore James
Album: The Blues
VideoID: 6koa37cPnAQ

Title: Crying Won't Make Me Stay
Artist: R.L. Burnside
Album: Mississippi Hill Country Blues
VideoID: BHUhx6JMrTE

Title: Worried Mind Blues
Artist: Fred McDowell
Album: Fred McDowell: The Alan Lomax Recordings
VideoID: DI82cMEhGTI

Title: Hot Resin (Remixed)
Artist: The Blackwater Fever
Album: In Stereo (Remixed & Remastered)
VideoID: MAaGccUll_w

Title: Death Letter Blues
Artist: Son House
Album: Father Of The Delta Blues: The Complete 1965 Sessions
VideoID: 149RjCpglYI

Title: Blues Run the Game (2001 - Remaster)
Artist: Jackson C. Frank
Album: Jackson C. Frank (2001 - Remaster)
VideoID: RyI7ph709x4

Title: Act Like You Love Me
Artist: Jimmy Rogers
Album: Blues Follow Me All Day Long: The Complete Shelter Recordings Of Jimmy Rogers / Chicago Blues Master
VideoID: o7HReNgpgVc

Title: Born Blind
Artist: Sonny Boy Williamson
Album: His Best
VideoID: DXH-k1TJKp0

Title: Keep Me
Artist: The Black Keys
Album: Rubber Factory
VideoID: CZHDxTAUJWE

Title: The Railroad
Artist: Goodnight, Texas
Album: A Long Life of Living
VideoID: M7s2AAO4czI

Title: If You Live
Artist: Mose Allison
Album: Creek Bank
VideoID: uvxanpFrKrw

Title: Son's Blues
Artist: Son House
Album: Son House Live At The Gaslight Cafe Jan 3rd 1965
VideoID: BkTUWwRZOL8

Title: You're Gonna Miss Me When I'm Gone (No. 1) (Plantation Recording)
Artist: Muddy Waters
Album: The Complete Plantation Recordings
VideoID: Dlx5jjqAbwc

Title: Pocket Knife Blues
Artist: Peetie Wheatstraw
Album: Peetie Wheatstraw Vol. 7 1940-1941
VideoID: nBGloVKAUyU

Title: Walking Blues
Artist: Big Mama Thornton
Album: Hound Dog / The Peacock Recordings
VideoID: JObMhKnuwV8

Title: Cross Road Blues
Artist: Robert Johnson
Album: King of the Delta Blues Singers (1961)
VideoID: bJ_7nYEpkBo

Title: A Fool for You
Artist: Ray Charles
Album: Ray Charles (aka: Hallelujah, I Love Her So)
VideoID: LCR7XVcvApQ

Title: Whiskey Head Woman
Artist: Tommy McClennan
Album: Tommy McClennan Vol. 1 "Whiskey Head Woman"
VideoID: mVVLjQ-JL3I

Title: Greyhound Bus Station
Artist: R.L. Burnside
Album: Mississippi Hill Country Blues
VideoID: NLYEozvYMsU

Title: Gate's Salty Blues
Artist: Clarence "Gatemouth" Brown
Album: The Peacock Recordings: 1949-1959
VideoID: B-4MGqQaIcI

Title: Crossroads (Live)
Artist: Cream
Album: Eric Clapton: Life In 12 Bars (Original Motion Picture Soundtrack)
VideoID: KcaCB_2MxJg

Title: Just Got Back from Baby's
Artist: ZZ Top
Album: ZZ Top's First Album
VideoID: sECASYZakHE

Title: I Don't Want No Woman
Artist: L.C. Lightnin Jr. Williams
Album: The Mercury Blues Story (1945-1955) - Southwest Blues, Vol. 2
VideoID: 3LQj4X-JNtk

Title: Who's Been Talking?
Artist: Howlin' Wolf
Album: Howlin' Wolf
VideoID: fX0sgKmSZ34

Title: I Can't Hear Nothing But The Blues
Artist: Albert King
Album: I Wanna Get Funky
VideoID: MxdmlAxyV3M

Title: You've Got My Mind Messed Up
Artist: James Carr
Album: A Man Needs a Woman
VideoID: 8nK9nlNX4dU

Title: Guitar Blues
Artist: Ray Charles
Album: Sittin' In With Harlem Jade & Jax, Vol. 2
VideoID: 8NW3-4bdvIg

Title: I’m The Midnight Creeper
Artist: Eddie "Cleanhead" Vinson
Album: The Very Best Of
VideoID: D-XQ7FTx2tM

Title: Troubles, Troubles, Troubles
Artist: B. B. King
Album: Blues Giants
VideoID: u8A4Subw7Xo

Title: Blue Monday Hangover
Artist: Albert Collins
Album: Deluxe Edition
VideoID: AvSwwPwu00c

Title: Walkin' Blues
Artist: Robert Johnson
Album: King of the Delta Blues Singers (1961)
VideoID: Gn9tDgSYxUw

Title: What'd I Say?
Artist: Lightnin' Hopkins
Album: Lightnin'!
VideoID: crpFPqIhosI

Title: Crossroad Blues
Artist: Robert Johnson
Album: The Essential Country Blues Guitar Collection (Vol.3)
VideoID: P_FvygWWRhc

Title: Red House
Artist: The Jimi Hendrix Experience
Album: Smash Hits
VideoID: HVaCfwjl_gM

Title: Pain in My Heart
Artist: Otis Redding
Album: Pain in My Heart
VideoID: T0w99HuHcK0

Title: Fine And Mellow
Artist: Billie Holiday & Her Orchestra
Album: Billie Holiday
VideoID: wNj409R8JWE

Title: Good Times
Artist: Aretha Franklin
Album: I Never Loved a Man the Way I Love You
VideoID: ryDlxlMPWXw

Title: Captain, Captain!
Artist: Mance Lipscomb
Album: Captain, Captain!
VideoID: -Wp_0pAf4hM

Title: Good Times Bad Times (Remaster)
Artist: Led Zeppelin
Album: Led Zeppelin (Remaster)
VideoID: lsZG7n7ries

Title: So Tired
Artist: Roy Milton
Album: Jazz Greats: Carmen McCrae, Art Farmer, Count Basie and More
VideoID: ypyI9IWFnag

Title: All Along The Watchtower
Artist: Jimi Hendrix
Album: Suspicious! Moment of Forever
VideoID: FQ-336hqi2s

Title: Poontang
Artist: T-Bone Walker
Album: Good Feelin'
VideoID: 83nSShBaPoE

Title: Checkin' On My Baby
Artist: Junior Wells, Otis Rush, Jack Myers, Freddie Below
Album: American Folk Blues Festival (66)
VideoID: gCdflxfCWho

Title: Grinnin' in Your Face
Artist: Son House
Album: Father Of The Delta Blues: The Complete 1965 Sessions
VideoID: 0to4rm6qkCU

Title: The Right Time
Artist: Ray Charles
Album: The Genius Sings the Blues (Mono)
VideoID: rxtlEhNggVY

Title: Personal Manager (Take 15 - Alternate)
Artist: Albert King
Album: Born Under A Bad Sign (Alternate Takes) EP
VideoID: rI27-UGmXe4

Title: Somebody Been Talkin'
Artist: Homesick James And His Dusters
Album: Chicago / The Blues / Today!
VideoID: hRsKPiQCEjc

Title: Hey Joe
Artist: The Jimi Hendrix Experience
Album: Are You Experienced
VideoID: Smp6AepJIhM

Title: Rainin' In My Heart
Artist: Slim Harpo
Album: Sings Raining In My Heart
VideoID: FkOoxzgJ6XM

Title: Louise McGhee
Artist: Son House
Album: Father Of The Delta Blues: The Complete 1965 Sessions
VideoID: GY7yZiIG-Aw

Title: Shake It For Me
Artist: Howlin' Wolf
Album: Howlin' Wolf
VideoID: Umq-L-CNiX0

Title: Crawlin' King Snake
Artist: Williams Big Joe
Album: The Ultimate Jazz Archive 12 - Blues (2 Of 4)
VideoID: _AaVUj5_n4Y

Title: Death Letter
Artist: The White Stripes
Album: De Stijl
VideoID: ba0IunweO5Q

Title: Mind Reader Blues
Artist: Bertha Lee
Album: Dry Well Blues (The Complete Recordings 1930 & 1934)
VideoID: _rCswNoJnLI

Title: Sugar Mama Blues
Artist: John Lee 'Sonny Boy' Williamson
Album: Blue Bird Blues
VideoID: OlOC8Nnpu5U

Title: Have You Ever Loved a Woman
Artist: Freddie King
Album: Kings of King
VideoID: JmDVx1MS_Jo

Title: Born Under A Bad Sign (with Stevie Ray Vaughan)
Artist: Albert King
Album: Stax Profiles: Albert King
VideoID: BB0uHb9BCxw

Title: One Bourbon, One Scotch, One Beer (2007 - Remaster)
Artist: John Lee Hooker
Album: Chill Out
VideoID: etssC5ZEHxQ

Title: When The Levee Breaks
Artist: Memphis Minnie
Album: The Roots of Led Zeppelin
VideoID: h8R3Oy28BKM

Title: The Natchez Burnin'
Artist: Howlin' Wolf
Album: The Real Folk Blues
VideoID: byDo89PdXGk

Title: Meet Me in the City
Artist: The Black Keys
Album: Chulahoma
VideoID: 5h9giEUguGs

Title: Crosscut Saw
Artist: Albert King
Album: Born Under A Bad Sign
VideoID: wUBMJk3syzI

Title: Let Me Love You Baby (Single Version)
Artist: Buddy Guy
Album: 20th Century Masters: The Millennium Collection: Best of Buddy Guy
VideoID: fgw4hvLy8BA

Title: Prisoner Of Love
Artist: Etta James
Album: Jazz
VideoID: O6yTbTe3kTk

Title: Ticket Agent
Artist: Lil' Son Jackson
Album: Blues Come to Texas
VideoID: ZHWTbE2ZN6U

Title: All My Love In Vain
Artist: Sonny Boy Williamson
Album: Down And Out Blues
VideoID: qga19cbXvv4

Title: Born With The Blues
Artist: Memphis Slim
Album: Absolutely the Best of Blues
VideoID: xSTNY3MzePc

Title: Champagne & Reefer
Artist: Muddy Waters
Album: King Bee
VideoID: rea4Stp0SeE

Title: Hardtime Killing Floor Blues
Artist: Skip James
Album: The Complete Greatest Of The Delta Blues Singers Recordings (Hd Remastered, Restored Edition, Doxy Collection)
VideoID: Wp1hKpIKzNE

Title: (I'm Your) Hoochie Coochie Man
Artist: Muddy Waters
Album: The Best Of Muddy Waters
VideoID: PtqzDuoKhpI

Title: Me and the Devil Blues
Artist: Robert Johnson
Album: King Of The Delta Blues Singers
VideoID: p9CDKtc1Cno

Title: I'm Goin' Home
Artist: Charley Patton
Album: Charley Patton, Vol. 1
VideoID: AzRuGcEcaVo

Title: Drifting Blues
Artist: Snooks Eaglin
Album: New Orleans Street Singer
VideoID: 0cNbufPYaNQ

Title: Cross Road Blues
Artist: Robert Johnson
Album: Best of the Delta Blues
VideoID: QDfw2ZjtWsQ

Title: Standing At the Crossroads
Artist: Elmore James
Album: Blues Duster
VideoID: rqg767YC6jM

Title: Big Boss Man
Artist: Jimmy Reed
Album: The Music Never Stopped: Roots Of The Grateful Dead
VideoID: 7gCej8h1IIo

Title: You're Killing My Love
Artist: Otis Rush
Album: Mourning In The Morning
VideoID: PLE6UW4yhKA

Title: My Heart Beat Like A Hammer (Take 2)
Artist: Fleetwood Mac
Album: Fleetwood Mac
VideoID: zsVOvrrA3GE

Title: Crossroads Blues
Artist: Robert Johnson
Album: King of the Delta Blues SIngers
VideoID: ZwAhSaZXq8s

Title: Hard Time Killing Floor Blues (Remastered 2024)
Artist: Skip James
Album: Today! (Remastered 2024)
VideoID: -tzvaZ3x9tI

Title: Rollin' Stone
Artist: Muddy Waters
Album: Muddy Waters Sings Delta Blues
VideoID: N4ZWrGZlxc8

Title: When My Train Pulls In (Solo Acoustic) [Live] (Solo Acoustic; Live)
Artist: Gary Clark Jr.
Album: The Bright Lights EP
VideoID: d1fFyf_sbDI

Title: Pride and Joy
Artist: Stevie Ray Vaughan & Double Trouble
Album: Texas Flood (Legacy Edition)
VideoID: Chk4tCMRBxk

Title: Thousand Miles from Nowhere
Artist: Clarence Edwards, Cornelius Edwards, & Butch Cage
Album: Country Negro Jam Session
VideoID: AUtDsHqpd_0

Title: Cincinnati Flow Rag
Artist: Reverend Gary Davis
Album: Blues & Ragtime (Live)
VideoID: CJqwsIo2NIE

Title: My Baby's Gone
Artist: Tommy McClennan
Album: The Very Best Of
VideoID: 1lGct_aPS0Y

Title: Sad Days, Lonely Nights (Full Band Version)
Artist: Junior Kimbrough
Album: Sad Days, Lonely Nights
VideoID: mDwDRQmtKB4

Title: Done Somebody Wrong
Artist: Elmore James
Album: Shake Your Moneymaker: The Best of the Fire Sessions
VideoID: tgt1EXbKbF0

Title: Blind Love
Artist: Howlin' Wolf
Album: Howlin' Wolf
VideoID: A4DieCrPBmQ

Title: Gone so Long
Artist: R.L. Burnside
Album: Mississippi Hill Country Blues
VideoID: yPgQUnw8cUg

Title: Meet Me in the City
Artist: Junior Kimbrough
Album: Meet Me in the City
VideoID: V94fxtPd1Nk

Title: Catfish Blues (Live)
Artist: Gary Clark Jr.
Album: Catfish Blues (Live)
VideoID: yge18n-ZQw4

Title: Stand by Me
Artist: Otis Redding
Album: Pain in My Heart
VideoID: IatStctYBPw

Title: Moanin' Blues
Artist: John Lee Hooker
Album: I'm In The Mood
VideoID: EzzouzKQEC8

Title: I'm A King Bee
Artist: Slim Harpo
Album: Sings Raining In My Heart
VideoID: hnVnrn4zVF4

Title: Rollin' Stone
Artist: Muddy Waters
Album: The Best Of Muddy Waters
VideoID: gwJZcNNxdck

Title: Where Did You Sleep Last Night (Live)
Artist: Nirvana
Album: MTV Unplugged In New York (25th Anniversary)
VideoID: c0wEcIPupNc

Title: My Baby's Doggin' Me
Artist: Big Joe Williams
Album: Big Joe Williams And The Stars Of Mississippi Blues
VideoID: kElKF-o8yAE

Title: You Was Wrong
Artist: Freddie King
Album: Texas Cannonball
VideoID: 1vrk9QqeuAw

Title: Tell Me Man Blues
Artist: Charley Patton with Henry Sims
Album: Charley Patton Vol. 3 (1929 - 1934)
VideoID: EOkIazVPwEo

Title: Bring Me My Shotgun
Artist: Lightnin' Hopkins
Album: The Best of Lightnin' Hopkins
VideoID: 3o1bj2NlTzU

Title: Crow Jane
Artist: Skip James
Album: Blues From The Delta
VideoID: vn2t368yLsw

Title: Boogie Chillun
Artist: John Lee Hooker
Album: Boogie Chillun
VideoID: 7vZ09iuW7uc

Title: I'm Good For Nothing
Artist: Jimmy Dawkins
Album: Fast Fingers
VideoID: kPLB-B50zUs

Title: Going To New Orleans
Artist: Tabby Thomas
Album: Hoo Do Man
VideoID: d8ANsVwTc8w

Title: Keep Your Hands off Her
Artist: The Black Keys
Album: Chulahoma
VideoID: vBUhTM9M3lc

Title: Boom Boom/Strange Brew (Live)
Artist: Buddy Guy
Album: Live At Legends
VideoID: vXqLtqqvg0g

Title: You Know I Love You
Artist: B.B. King
Album: Singin' The Blues
VideoID: rFisqNhAf1I

Title: Good Morning Little School Girl
Artist: Muddy Waters
Album: Folk Singer (Expanded Edition)
VideoID: EOCgOX2dtPQ

Title: Death Letter Blues
Artist: Son House
Album: Father Of The Delta Blues: The Complete 1965 Sessions
VideoID: wy3ugz4S2y0

Title: Spokey Dokey
Artist: Seatbelts
Album: COWBOY BEBOP (Original Motion Picture Soundtrack)
VideoID: Amsp6S2lUwo

Title: Groundhog Blues
Artist: Lil' Son Jackson
Album: Blues Come to Texas
VideoID: i0yihJQ27yg

Title: My Strange Man
Artist: Memphis Minnie
Album: Hoodoo Lady (1933-1937)
VideoID: 5SyV43rP-xA

Title: Sweet Thang
Artist: Shuggie Otis
Album: Shuggie's Boogie: Shuggie Otis Plays The Blues
VideoID: wk94HIodJ48

Title: I'm Begging You
Artist: Lightnin' Hopkins
Album: Mojo Hand Anthology
VideoID: 0iogbdYUI2g

Title: Ain't No Mountain High Enough
Artist: Marvin Gaye
Album: A Motown Thanksgiving Celebration
VideoID: WHc7dk8RebM

Title: Cottonfield Blues, Pt. 1
Artist: Garfield Akers
Album: Mississippi Masters: Early American Blues Classics 1927 - 35
VideoID: dUKcpeVvHsU

Title: Don't Throw Your Love On Me So Strong (American Folk Blues Festival Version)
Artist: T-Bone Walker
Album: Ultimate Blues Guitar
VideoID: DkKZPAj4Cuo

Title: BB Gun
Artist: Roger Alan Wade
Album: All Likkered Up
VideoID: iYgVO77HrLI

Title: Gypsy Woman Blues
Artist: Papa Charlie's Boys
Album: The McCoy Brothers (Charlie & Joe McCoy) Vol. 2 (1936-1944)
VideoID: FCvHEXdtPl4

Title: Smokestack Lightnin'
Artist: Howlin' Wolf
Album: Moanin' In The Moonlight
VideoID: PnXTpkugcHo

Title: When the Levee Breaks (Remaster)
Artist: Led Zeppelin
Album: Led Zeppelin IV (Deluxe Edition)
VideoID: FFDYuO53BUk

Title: Machine Gun (Live)
Artist: Jimi Hendrix
Album: Band Of Gypsys (50th Anniversary / Live At Fillmore East, 1970)
VideoID: Lw2L_vGUMtE

Title: Baby, Please Don`t Go
Artist: John Lee Hooker
Album: Sweet Temptation
VideoID: 0it7r8u4YdM

Title: I've Been Loving You Too Long
Artist: Otis Redding
Album: Otis Blue
VideoID: Nj_7qO58mU8

Title: Hobo Blues
Artist: John Lee Hooker
Album: Huckle Up Baby
VideoID: fy-WDdCOxtg

Title: Tennessee Blues
Artist: Clarence "Gatemouth" Brown
Album: Timeless
VideoID: Q29FA-UTlpE

Title: One Bourbon, One Scotch, One Beer
Artist: George Thorogood & The Destroyers
Album: George Thorogood And The Delaware Destroyers (Bonus Track Version)
VideoID: sDf0IwXoOmY

Title: Beat the Devil's Tattoo
Artist: Black Rebel Motorcycle Club
Album: Beat the Devil's Tattoo
VideoID: Ay3Izb6sGAo

Title: Tell Me Man Blues
Artist: Henry Sims
Album: Beautiful Blues Memories, Vol. 1
VideoID: vQClDmtYBys

Title: Boom Boom
Artist: John Lee Hooker
Album: John Lee Hooker
VideoID: MS2Lu9wzQoY

Title: Come On in My Kitchen
Artist: Robert Johnson
Album: Robert Johnson's Blues Collection
VideoID: Ryl62yEEo0k

Title: Nobody's Fault But Mine
Artist: Blind Willie Johnson
Album: The Gospel Sound
VideoID: TjazJ39k1GY

Title: Blues Power (Live)
Artist: Albert King
Album: Live In the 70s
VideoID: tqK1a_onxMo

Title: Hey What
Artist: The Boonx
Album: Facing The Music
VideoID: -yaaa2YTMOQ

Title: To Know You Is To Love You
Artist: B.B. King
Album: To Know You Is To Love You
VideoID: -9VQXP-vNl0

Title: Hey Hey
Artist: Big Bill Broonzy
Album: An Introduction To Big Bill Broonzy
VideoID: mwWGkUChlVs

Title: Rats and Roaches in My Kitchen
Artist: Silas Hogan
Album: Louisiana Blues
VideoID: 5-CJcXfydV0

Title: Crazy Cryin' Blues
Artist: Memphis Minnie & Kansas Joe
Album: Memphis Minnie & Kansas Joe Vol. 3 (1931 - 1932)
VideoID: AIAw2fAFNMA

Title: Boogie Children
Artist: John Lee Hooker
Album: I'm John Lee Hooker
VideoID: L_X-ELsy29A

Title: I Won't Stand In Your Way
Artist: Stray Cats
Album: Rant N' Rave With The Stray Cats
VideoID: adzxbsSp3p0

Title: Hard Time Killin? Floor Blues
Artist: Skip James
Album: Illinois Blues
VideoID: CUIF8cGf3ow

Title: Thank You Mr. Poobah
Artist: The Paul Butterfield Blues Band
Album: The Paul Butterfield Blues Band
VideoID: LEssH4XNkFA

Title: Chicken In The Corn
Artist: Brushy One String
Album: The King of One String (Acoustic)
VideoID: EqZ1fi-M6RM

Title: Money (That's What I Want)
Artist: Buddy Guy
Album: The Complete Vanguard Recordings
VideoID: gcG2ZYNCX1A

Title: Ball and Biscuit

## Upload playlist from tsv backup

In [ ]:
PLAYLIST_NAME = 'zz not like 3'
playlist_file = os.path.join(PLAYLIST_TSV_DIR, PLAYLIST_NAME + '.tsv')
Y.playlist_from_tsv(playlist_file, ignore_banned=True, sort_by_index=True)
# for y in [2020, 2021, 2022, 2023, 2024]:
#   PLAYLIST_NAME = f'y {y} top'
#   playlist_file = os.path.join(PLAYLIST_TSV_DIR, PLAYLIST_NAME + '.tsv')
#   Y.playlist_from_tsv(playlist_file, ignore_banned=True, sort_by_index=True)

### Playlist radio and like mapping helpers

In [ ]:
# Get possible tracks to add to radio like playlist map
import pandas as pd
radio_map = pd.read_csv('..\\playlists\\_ytmusic_radio_to_like_pl_map.tsv', sep='\t')
radio_map = dict(zip(radio_map['radio_playlist'], radio_map['like_playlist']))
# radio_map
all_playlists = frozenset(Y.playlists['title'].unique())
add_to_radio_map = []
for t in sorted(all_playlists):
  if not t.endswith("radio"):
    continue
  if t in radio_map:
    continue  
  if t.replace('radio', 'like') in all_playlists:
   continue
  add_to_radio_map.append(t)
  print(t)

Rock modern The New Age of Classic radio
christmas crooners radio
hiphop get dumb radio
instrumental ambient piano radio
instrumental piano classical radio
punk skate or die radio
xr AtmosphericDnB radio
xr DoomMetal radio
xr Flamenco radio
xr Instrumentals radio
xr ModernRockMusic radio
xr OutlawCountry radio
xr SpaceMusic radio
xr Techno radio
xr TropicalHouse radio
xr acidhouse radio
xr animemusic radio
xr bossanova radio
xr chicagohouse radio
xr melodichouse radio
xs DEZKO ASCEND radio
xs Discord Favorites radio
xs Liquid Drum And Bass radio
zp Dilla radio
['Rock modern The New Age of Classic radio', 'christmas crooners radio', 'hiphop get dumb radio', 'instrumental ambient piano radio', 'instrumental piano classical radio', 'punk skate or die radio', 'xr AtmosphericDnB radio', 'xr DoomMetal radio', 'xr Flamenco radio', 'xr Instrumentals radio', 'xr ModernRockMusic radio', 'xr OutlawCountry radio', 'xr SpaceMusic radio', 'xr Techno radio', 'xr TropicalHouse radio', 'xr acidhouse radio', 'xr animemusic radio', 'xr bossanova radio', 'xr chicagohouse radio', 'xr melodichouse radio', 'xs DEZKO ASCEND radio', 'xs Discord Favorites radio', 'xs Liquid Drum And Bass radio', 'zp Dilla radio']

In [ ]:
# Get possible like playlists, then manually edit and add to _like_playlist.tsv
for _, row in Y.playlists.iterrows():
  t = row['title']
  if not (t.endswith("like") or t.endswith("radio") or t.endswith("albums")):
    print(t)

Liked Music
2022 Recap
2023 Recap
ambiant electro
ambient
ambient BOC
ambient Dream Pop Deep Sleep
ambient haunting harmonious
ambient Indie Synths
ambient japan
beats
beats 2010s wonky LA scene
beats cosmic Slop
beats dj
beats instrumental
Beats Lofi
beats Soulful Instrumentals
bluegrass billy
blues
blues chicago
blues delta roots
blues electric
blues texas roots
Bossa Nova
Brass n chill
Chill Supermix
Chillwave
Discover Weekly
electronic
electronic 1990s electronica
electronic 1990s late 1980s House
electronic 2000s
electronic 2010s
electronic Analog Grooves
electronic big beats
electronic chill
electronic Dance
electronic deep house
electronic dubstep uk
electronic Focus
electronic hard dj
electronic house
electronic house big bass
electronic house dj
electronic house french touch
electronic house funk
electronic House Soulful
electronic House Special
electronic indie essentials
electronic Innerwaves
electronic jaar
electronic new indie beats
electronic soft pad
electronic trance dj
electronic uk
electronic witch house
Episodes for Later
Folk
folk 1960s
folk fall indie chill
future bass
future beats
future garage
garage rock
goth 1980s
Grunge
Grunge Seattle
hawaiian steel guitar
Hip Hop 1980s
Hip Hop 1990s
Hip Hop 1990s east coast
Hip Hop 1990s G funk
Hip Hop 1990s west Coast
Hip Hop 2000s
Hip Hop 2000s southern
Hip Hop Hits
hiphop
hiphop futurebeats
hiphop indie
hiphop jazzy
hiphop modern
hiphop old school
hiphop soul good vibe
hiphop Soulquarians
hiphop wrist twistin
important videos
indie
Indie 1990s Rock
Indie 2000s
indie folk
indie krill vibe
indie loose
Indie psych
Instrumental Acoustic Guitar Explorations
jazz
jazz ballads
jazz blue note
jazz blue note latin
jazz cool
Jazz drumming
jazz funk cortex vibe
jazz gloom smooth
jazz guitar
jazz gypsy
jazz japanese
jazz noir
jazz sunrise
my balls your chill
nudisco
nudisco smooth
Oldies
oldies 1930-40s naptime
oldies 1950s
oldies 1960s
oldies doo wop
post rock slow core
Post-Punk 1970s-1980s
psych rock modern
Psychedelic 1960s Orchestra
psychedelic classic rock
punk 1970s
Reggae
reggae classic
reggae covers
Reggae Dub
reggae modern
rock 1950s roots
rock 1960s baroque
rock 1960s classic
rock 1967
rock 1967 Monterey Pop Festival
Rock 1967-1969
rock 1969 Woodstock
rock 1970s classic
rock 1970s pop singer songwriters
Rock 1970s progressive
rock 1980s college on air
Rock 1980s Pop New Wave
rock 1990s
rock 1990s alternative
rock 2000s
rock blues
rock classic
rock Deep Cut Kick Back
rock instrumentals classic vintage
rock krautrock
rock modern chill
rock Motorik
rock proto metal
Rock Sand Dunes & Guitars
rock stoner sludge dank
rock surf
rock surf japanese takeshi teraichi
rock surf modern
rockabilly
Shoegaze
Shoegaze Radio
soul 1960s
Soul Classic Sunshine
soul funk
soul funk greasy
soul motown
soul rnb dj
soul rock covers
summertime covers
trip hop
triphop bristol sound
xp grateful dead live
xr 70sMusic albums
xr 90shiphop albums
xr 90sPunk albums
xr ambientmusic albums
xr bluesrock albums
xr bossanova albums
xr chillmusic albums
xr chillwave albums
xr DreamPop albums
xr dub albums
xr ElectronicMusic albums
xr folk albums
xr futurebass albums
xr futurebeats albums
xr futuresynth albums
xr hiphop albums
xr idm albums
xr indie albums
xr IndieFolk albums
xr jazz albums
xr jazznoir albums
xr krautrock albums
xr lofihiphop albums
xr minimal albums
xr PostRock albums
xr psychedelicrock albums
xr PunkRock albums
xr rainymood albums
xr reggae albums
xr shoegaze albums
xr SoundsVintage albums
xr stonerrock albums
xr theOverload albums
xr treemusic albums
xr triphop albums
xr VintageObscura albums
xr witch-house albums
y 1950s top
y 1960s top
y 1970s top
y 1980s top
y 1990s top
y 2000s top
y 2005s top
y 2010 top
y 2011 top
y 2012 top
y 2013 top
y 2014 top
y 2015 top
y 2016 top
y 2017 top
y 2018 top
y 2018 top 50 albums
y 2019 top
y 2019 top 50 albums
y 2020 top
y 2021 top
y 2022 top
zp Beatles
zp dangermouse
zp Dilla
zp DJ Premier
zp elvis
zp kanye
zp lynchian
zp Pink Floyd epic
zp RZA
zp True Detective
zp world of elliot smith
zp world of kurt cobain
zp world of velvet underground
zz not like 2
zzy 2017 unrated albums
zzy 2018 unrated albums
zzy 2018-2019 ambient albums unrated
zzy 2019 unrated albums
zzy 2020 unrated albums
zzy 2021 unrated albums
zzy 2022 unrated albums
zzy 2023 unrated albums
zzz dj edits
zzz dj fx drumz vox
zzz dj gold
zzz dj history 2015y04m11d 02h18m16s
zzz dj mixes library
zzz dj mixes traktor
zzz dj remix
zzz dj thumbs up
zzz Live concert phone recordings

## Query

In [ ]:
Y.query_by_title(playlist_name)

title                                                 jazz radio
playlistId                    PLWptjpDqazOxgrXKM4xfJ-SBRahEDfXmG
thumbnails     [{'url': 'https://yt3.googleusercontent.com/zS...
description                                  Jake G • 797 tracks
count                                                        797
author         [{'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFU...
Name: 20, dtype: object

### Rename Batch Playlists

In [ ]:
VERBOSE = True
DRY_RUN = True

# Rename original subreddit playslists tor shorter no . or _ name
# See: notebooks/old/ytmusic_rename_some_playlists.ipynb
# Example: x_r.bluegrass_tracks_like --> xr bluegrass like
for i, row in Y.playlists.iterrows():
    playlist_name = row['title']
    if playlist_name.startswith("x_r."):
        new_name = playlist_name.replace("x_r.", "xr ").replace("_tracks_", " ").replace("_albums", " albums") 
        if VERBOSE:
            print(f"Renaming: {playlist_name} --> {new_name}")
        if not DRY_RUN:
            Y.rename_playlist(row['playlistId'], new_name)
            
# Manually fix these
Y.find_playlists_with_special_chars(special_chars=["_", "/", ".", ":", ",", "x.r", "x.s" "y_", "x.sp", "Produced", "p_"])

Renaming: x_r.2000smusic_tracks_like --> xr 2000smusic like
Renamed playlist with ID 'PLWptjpDqazOxnmxikFDKOXszYFONGWs8U' to 'xr 2000smusic like'
Renaming: x_r.2000smusic_tracks_radio --> xr 2000smusic radio
Renamed playlist with ID 'PLWptjpDqazOzwVaW_CNc6xtp7v_stZ_dX' to 'xr 2000smusic radio'
Renaming: x_r.2010smusic_tracks_like --> xr 2010smusic like
Renamed playlist with ID 'PLWptjpDqazOwWltLPE8IThgPJeElLQIUO' to 'xr 2010smusic like'
Renaming: x_r.50sMusic_tracks_like --> xr 50sMusic like
Renamed playlist with ID 'PLWptjpDqazOwCLs4ZOeyb_Lg4IgAGlg2L' to 'xr 50sMusic like'
Renaming: x_r.60sMusic_tracks_like --> xr 60sMusic like
Renamed playlist with ID 'PLWptjpDqazOzTAvihnt0PZpLX-bj0JJh2' to 'xr 60sMusic like'
Renaming: x_r.70sMusic_albums --> xr 70sMusic albums
Renamed playlist with ID 'PLWptjpDqazOyo7RbE6Pjv1HJUa61TRhPc' to 'xr 70sMusic albums'
Renaming: x_r.70sMusic_tracks_like --> xr 70sMusic like
Renamed playlist with ID 'PLWptjpDqazOyxy1ElEB7K1qG2A9Pie5ar' to 'xr 70sMusic like'
Renaming: x_r.70sMusic_tracks_radio --> xr 70sMusic radio
Renamed playlist with ID 'PLWptjpDqazOythRAN52Cp8m1HmbU6Gm-m' to 'xr 70sMusic radio'
Renaming: x_r.80sHipHop_tracks_like --> xr 80sHipHop like
Renamed playlist with ID 'PLWptjpDqazOxMtDLxJkybVUWA_M1mh3Wx' to 'xr 80sHipHop like'
Renaming: x_r.80sHipHop_tracks_radio --> xr 80sHipHop radio
Renamed playlist with ID 'PLWptjpDqazOx6u_-ogCY8IHy6XsL9Coc_' to 'xr 80sHipHop radio'
Renaming: x_r.80sMusic_tracks_like --> xr 80sMusic like
Renamed playlist with ID 'PLWptjpDqazOzghbwsfgt5t0h2BBaf-RyR' to 'xr 80sMusic like'
Renaming: x_r.80sMusic_tracks_radio --> xr 80sMusic radio
Renamed playlist with ID 'PLWptjpDqazOx9jA9hOj_3xjm5nk0OgCsw' to 'xr 80sMusic radio'
Renaming: x_r.90sAlternative_tracks_like --> xr 90sAlternative like
Renamed playlist with ID 'PLWptjpDqazOxYpiFn9JMLp-Qv1JXFYfAO' to 'xr 90sAlternative like'
Renaming: x_r.90sAlternative_tracks_radio --> xr 90sAlternative radio
Renamed playlist with ID 'PLWptjpDqazOx0ZPDpoI13GxAC-6Xl0ElT' to 'xr 90sAlternative radio'
Renaming: x_r.90shiphop_albums --> xr 90shiphop albums
Renamed playlist with ID 'PLWptjpDqazOzDOIhVuC4HFb6AjIEMzBJY' to 'xr 90shiphop albums'
Renaming: x_r.90shiphop_tracks_radio --> xr 90shiphop radio
Renamed playlist with ID 'PLWptjpDqazOznLr_m9537w6vk-z9BI4GC' to 'xr 90shiphop radio'
Renaming: x_r.90sMusic_tracks_like --> xr 90sMusic like
Renamed playlist with ID 'PLWptjpDqazOxdu65jPKja9Xl4mbZUMue3' to 'xr 90sMusic like'
Renaming: x_r.90sMusic_tracks_radio --> xr 90sMusic radio
Renamed playlist with ID 'PLWptjpDqazOz6MRK5LIUjOUfZoNOBcCP0' to 'xr 90sMusic radio'
Renaming: x_r.90sPunk_albums --> xr 90sPunk albums
Renamed playlist with ID 'PLWptjpDqazOwX0HdvBfZasy-tnc_QKT6w' to 'xr 90sPunk albums'
Renaming: x_r.90sPunk_tracks_like --> xr 90sPunk like
Renamed playlist with ID 'PLWptjpDqazOxKU9mR3l0NYyaExRE9oNXM' to 'xr 90sPunk like'
Renaming: x_r.90sPunk_tracks_radio --> xr 90sPunk radio
Renamed playlist with ID 'PLWptjpDqazOw9jR4vJ4hxYjWSRcfKXDw2' to 'xr 90sPunk radio'
Renaming: x_r.90sRock_tracks_like --> xr 90sRock like
Renamed playlist with ID 'PLWptjpDqazOxGLrsXrjSkxjLjbXSLOYyo' to 'xr 90sRock like'
Renaming: x_r.90sRock_tracks_radio --> xr 90sRock radio
Renamed playlist with ID 'PLWptjpDqazOzqPaIvNXYOb2w7yoHA9qUb' to 'xr 90sRock radio'
Renaming: x_r.acidhouse_tracks_radio --> xr acidhouse radio
Renamed playlist with ID 'PLWptjpDqazOznDD4OM8UNSCjrbr_VuAZK' to 'xr acidhouse radio'
Renaming: x_r.AfricanMusic_tracks like --> xr AfricanMusic_tracks like
Renamed playlist with ID 'PLWptjpDqazOwNG87iuw5IeGrU9j-miAyV' to 'xr AfricanMusic_tracks like'
Renaming: x_r.AfricanMusic_tracks_radio --> xr AfricanMusic radio
Renamed playlist with ID 'PLWptjpDqazOyC_s0IfPGKojFb7-Ho0dfn' to 'xr AfricanMusic radio'
Renaming: x_r.ambientmusic_albums --> xr ambientmusic albums
Renamed playlist with ID 'PLWptjpDqazOyeOvTS3agi1ktHV3RJeGl4' to 'xr ambientmusic albums'
Renaming: x_r.ambientmusic_tracks_radio --> xr ambientmusic radio
Renamed playlist with ID 'PLWptjpDqazOzyZfT0wuLVN9UuA531T2gr' to 'xr ambientmusic radio'
Renaming: x_r.animemusic_tracks_radio --> xr animemusic radio
Renamed playlist with ID 'PLWptjpDqazOyEOrk0qaS6xI_mRgBGKPwE' to 'xr animemusic radio'
Renaming: x_r.AtmosphericDnB_tracks_radio --> xr AtmosphericDnB radio
Renamed playlist with ID 'PLWptjpDqazOzJ140Gc37FIOtFH0RQ5e9v' to 'xr AtmosphericDnB radio'
Renaming: x_r.bassheavy_tracks_like --> xr bassheavy like
Renamed playlist with ID 'PLWptjpDqazOwNa2uvyTomNHez2XNXYWrE' to 'xr bassheavy like'
Renaming: x_r.bassheavy_tracks_radio --> xr bassheavy radio
Renamed playlist with ID 'PLWptjpDqazOwGuWRQ-pxKEqq-gDV6ctC_' to 'xr bassheavy radio'
Renaming: x_r.bluegrass_tracks_like --> xr bluegrass like
Renamed playlist with ID 'PLWptjpDqazOzBK51Cor30APg41mvf5CqM' to 'xr bluegrass like'
Renaming: x_r.bluegrass_tracks_radio --> xr bluegrass radio
Renamed playlist with ID 'PLWptjpDqazOzrksluRsO1FsiXCnDNdO8A' to 'xr bluegrass radio'
Renaming: x_r.blues_tracks_radio --> xr blues radio
Renamed playlist with ID 'PLWptjpDqazOzT59L2yVpPw0RwsPbX7T22' to 'xr blues radio'
Renaming: x_r.bluesrock_albums --> xr bluesrock albums
Renamed playlist with ID 'PLWptjpDqazOyoPYxfEUhVYbaLjrQ4q2Wj' to 'xr bluesrock albums'
Renaming: x_r.bluesrock_tracks_like --> xr bluesrock like
Renamed playlist with ID 'PLWptjpDqazOyRAC1qj8EyV15i1AtcCRIa' to 'xr bluesrock like'
Renaming: x_r.bluesrock_tracks_radio --> xr bluesrock radio
Renamed playlist with ID 'PLWptjpDqazOyr4sjHXG4jktyZD9EFQu0P' to 'xr bluesrock radio'
Renaming: x_r.bossanova_albums --> xr bossanova albums
Renamed playlist with ID 'PLWptjpDqazOxkOgxmFKEj6m9S2mlZuCxq' to 'xr bossanova albums'
Renaming: x_r.bossanova_tracks_radio --> xr bossanova radio
Renamed playlist with ID 'PLWptjpDqazOyJQdzo8LbSfOJOBV4nbMNo' to 'xr bossanova radio'
Renaming: x_r.chicagohouse_tracks_radio --> xr chicagohouse radio
Renamed playlist with ID 'PLWptjpDqazOzwOd5TBZvCFqkwH5hcuMbu' to 'xr chicagohouse radio'
Renaming: x_r.chillmusic_albums --> xr chillmusic albums
Renamed playlist with ID 'PLWptjpDqazOylAeE0dryTfPVewK6JFI8L' to 'xr chillmusic albums'
Renaming: x_r.chillmusic_like --> xr chillmusic_like
Renamed playlist with ID 'PLWptjpDqazOyMYZwsBEBrXFs86cIwQY3_' to 'xr chillmusic_like'
Renaming: x_r.chillmusic_tracks_radio --> xr chillmusic radio
Renamed playlist with ID 'PLWptjpDqazOwSDNttFBRTKWEN9vXCudZQ' to 'xr chillmusic radio'
Renaming: x_r.chillwave_albums --> xr chillwave albums
Renamed playlist with ID 'PLWptjpDqazOx7zES4ZLvYXiSDhWYLDIw-' to 'xr chillwave albums'
Renaming: x_r.chillwave_tracks_like --> xr chillwave like
Renamed playlist with ID 'PLWptjpDqazOxrWgRrIJAw_hrw9r7m-Op1' to 'xr chillwave like'
Renaming: x_r.chillwave_tracks_radio --> xr chillwave radio
Renamed playlist with ID 'PLWptjpDqazOxKfSf-LuzkrrSCU9c7r1PF' to 'xr chillwave radio'
Renaming: x_r.dancepunk_tracks_like --> xr dancepunk like
Renamed playlist with ID 'PLWptjpDqazOzGvfDplNzfUaqG18n7NqjD' to 'xr dancepunk like'
Renaming: x_r.deepcuts_tracks_like --> xr deepcuts like
Renamed playlist with ID 'PLWptjpDqazOznA53pIVMHv9rWDerijlgt' to 'xr deepcuts like'
Renaming: x_r.deepcuts_tracks_radio --> xr deepcuts radio
Renamed playlist with ID 'PLWptjpDqazOw_YVGGeZwPIn9RjPXaPXyv' to 'xr deepcuts radio'
Renaming: x_r.deephouse_tracks_radio --> xr deephouse radio
Renamed playlist with ID 'PLWptjpDqazOyEgyc-s6xyaWW8eqz-uWk5' to 'xr deephouse radio'
Renaming: x_r.disco_tracks_like --> xr disco like
Renamed playlist with ID 'PLWptjpDqazOzD0k8DzLvbR3s5dGVAzSoO' to 'xr disco like'
Renaming: x_r.disco_tracks_radio --> xr disco radio
Renamed playlist with ID 'PLWptjpDqazOyJXtfYNJ8ITcmaLK4f1Xgy' to 'xr disco radio'
Renaming: x_r.DoomMetal_tracks_radio --> xr DoomMetal radio
Renamed playlist with ID 'PLWptjpDqazOzlh0jtPzHc22BER2aa9TQg' to 'xr DoomMetal radio'
Renaming: x_r.DreamPop_albums --> xr DreamPop albums
Renamed playlist with ID 'PLWptjpDqazOyKJngvlXF3_eziWI40DaiA' to 'xr DreamPop albums'
Renaming: x_r.DreamPop_tracks_like --> xr DreamPop like
Renamed playlist with ID 'PLWptjpDqazOxNP8n6ggwu9qjThbL79yDx' to 'xr DreamPop like'
Renaming: x_r.DreamPop_tracks_radio --> xr DreamPop radio
Renamed playlist with ID 'PLWptjpDqazOyq69B5z_xhrBR3NiZzSn7s' to 'xr DreamPop radio'
Renaming: x_r.dub_albums --> xr dub albums
Renamed playlist with ID 'PLWptjpDqazOyTC6_TwBwJMp1QNX6yWhnR' to 'xr dub albums'
Renaming: x_r.dub_tracks_radio --> xr dub radio
Renamed playlist with ID 'PLWptjpDqazOxmb4AqGjAgqrCHROt6gwre' to 'xr dub radio'
Renaming: x_r.ElectronicMusic_albums --> xr ElectronicMusic albums
Renamed playlist with ID 'PLWptjpDqazOyKYVbg5loXPOJqSIVqShC6' to 'xr ElectronicMusic albums'
Renaming: x_r.ElectronicMusic_tracks_radio --> xr ElectronicMusic radio
Renamed playlist with ID 'PLWptjpDqazOxsSGahESoQ6BucesbPEYv6' to 'xr ElectronicMusic radio'
Renaming: x_r.Elephant6_tracks_like --> xr Elephant6 like
Renamed playlist with ID 'PLWptjpDqazOyL3pzna7RXkF5mvWXudVJL' to 'xr Elephant6 like'
Renaming: x_r.Flamenco_tracks_radio --> xr Flamenco radio
Renamed playlist with ID 'PLWptjpDqazOzV5mbempxEdGlGEqyC2SSI' to 'xr Flamenco radio'
Renaming: x_r.folk_albums --> xr folk albums
Renamed playlist with ID 'PLWptjpDqazOxIDrzhvE4mPWWO_ADkkOZS' to 'xr folk albums'
Renaming: x_r.folk_tracks_radio --> xr folk radio
Renamed playlist with ID 'PLWptjpDqazOxuXl1qaKdISliflLUkYoQT' to 'xr folk radio'
Renaming: x_r.frenchhouse_tracks_radio --> xr frenchhouse radio
Renamed playlist with ID 'PLWptjpDqazOzrGEa9Snx_nzSPl4SsyNXR' to 'xr frenchhouse radio'
Renaming: x_r.funkhouse_tracks_radio --> xr funkhouse radio
Renamed playlist with ID 'PLWptjpDqazOyXxRd9Glpqo3_iuuqc_PiA' to 'xr funkhouse radio'
Renaming: x_r.futurebass_albums --> xr futurebass albums
Renamed playlist with ID 'PLWptjpDqazOyBWiRly7d4prEQW86PQxG5' to 'xr futurebass albums'
Renaming: x_r.futurebass_tracks_radio --> xr futurebass radio
Renamed playlist with ID 'PLWptjpDqazOz5SWdUFNnnd6ix0KHsYJAt' to 'xr futurebass radio'
Renaming: x_r.futurebeats_albums --> xr futurebeats albums
Renamed playlist with ID 'PLWptjpDqazOzaWK6GZuXGbJ3dOEkbfpOf' to 'xr futurebeats albums'
Renaming: x_r.futurebeats_tracks_like --> xr futurebeats like
Renamed playlist with ID 'PLWptjpDqazOzLcxklJYABdEIFf1iekeni' to 'xr futurebeats like'
Renaming: x_r.futurebeats_tracks_radio --> xr futurebeats radio
Renamed playlist with ID 'PLWptjpDqazOxluH9lkGBD2DELSnp8jTbi' to 'xr futurebeats radio'
Renaming: x_r.futurefunkairlines_tracks_like --> xr futurefunkairlines like
Renamed playlist with ID 'PLWptjpDqazOyv6M7A3L4ZuGj02rlbvYVV' to 'xr futurefunkairlines like'
Renaming: x_r.futurefunkairlines_tracks_radio --> xr futurefunkairlines radio
Renamed playlist with ID 'PLWptjpDqazOw6yhW9nzsRyjfrXa7T2Hi7' to 'xr futurefunkairlines radio'
Renaming: x_r.futuregarage_tracks_like --> xr futuregarage like
Renamed playlist with ID 'PLWptjpDqazOxU64hqdPGo4lBOEvPb7f9q' to 'xr futuregarage like'
Renaming: x_r.futuregarage_tracks_radio --> xr futuregarage radio
Renamed playlist with ID 'PLWptjpDqazOxwPYDZcENohM2Dy6iL96ln' to 'xr futuregarage radio'
Renaming: x_r.futuresynth_albums --> xr futuresynth albums
Renamed playlist with ID 'PLWptjpDqazOznIFYjUnrSPfHEeysVDJ3H' to 'xr futuresynth albums'
Renaming: x_r.futuresynth_tracks_like --> xr futuresynth like
Renamed playlist with ID 'PLWptjpDqazOx3z9jsMzNxLWAoKHuz9B1J' to 'xr futuresynth like'
Renaming: x_r.futuresynth_tracks_radio --> xr futuresynth radio
Renamed playlist with ID 'PLWptjpDqazOxpJkj8s_lXwCL4pYWf2RVJ' to 'xr futuresynth radio'
Renaming: x_r.GypsyJazz_tracks_radio --> xr GypsyJazz radio
Renamed playlist with ID 'PLWptjpDqazOxcJD67cX0acuvCGq07a9vZ' to 'xr GypsyJazz radio'
Renaming: x_r.HeadNodders_tracks_like --> xr HeadNodders like
Renamed playlist with ID 'PLWptjpDqazOzwxROuS5wrvJ_GcdiCbSVZ' to 'xr HeadNodders like'
Renaming: x_r.HeadNodders_tracks_radio --> xr HeadNodders radio
Renamed playlist with ID 'PLWptjpDqazOyqVztZW7UcBYG43OGjTyVE' to 'xr HeadNodders radio'
Renaming: x_r.hiphop_albums --> xr hiphop albums
Renamed playlist with ID 'PLWptjpDqazOzMHdEnLSHBipiaKFvb3nUN' to 'xr hiphop albums'
Renaming: x_r.hiphop_tracks_radio --> xr hiphop radio
Renamed playlist with ID 'PLWptjpDqazOzeAo9vwTCLDFn6iUuPG1_b' to 'xr hiphop radio'
Renaming: x_r.hiphopheadsnorthwest_tracks_radio --> xr hiphopheadsnorthwest radio
Renamed playlist with ID 'PLWptjpDqazOzmGhPoyQ-7ZiscEskrwXxi' to 'xr hiphopheadsnorthwest radio'
Renaming: x_r.house_tracks_like --> xr house like
Renamed playlist with ID 'PLWptjpDqazOxyqxyHQhfEbBteK6EEEsvT' to 'xr house like'
Renaming: x_r.house_tracks_radio --> xr house radio
Renamed playlist with ID 'PLWptjpDqazOzbpe3QluIciBNbXtvK0NAs' to 'xr house radio'
Renaming: x_r.idm_albums --> xr idm albums
Renamed playlist with ID 'PLWptjpDqazOwTPGnVsNOO9SJFmksR3rsu' to 'xr idm albums'
Renaming: x_r.idm_tracks_like --> xr idm like
Renamed playlist with ID 'PLWptjpDqazOw5h6jEMu5CIoC90DL6lzT9' to 'xr idm like'
Renaming: x_r.idm_tracks_radio --> xr idm radio
Renamed playlist with ID 'PLWptjpDqazOx0Ssimhci93TOt8SWvirVj' to 'xr idm radio'
Renaming: x_r.idm_tracks_radio --> xr idm radio
Renamed playlist with ID 'PLWptjpDqazOwrZlRFSf_oY_U-jXmYXEd7' to 'xr idm radio'
Renaming: x_r.indie_albums --> xr indie albums
Renamed playlist with ID 'PLWptjpDqazOzPas0DjKtPn1ksjqAwY1cD' to 'xr indie albums'
Renaming: x_r.indie_tracks_radio --> xr indie radio
Renamed playlist with ID 'PLWptjpDqazOxqPtEFPftaSK2ttqrckK45' to 'xr indie radio'
Renaming: x_r.IndieFolk_albums --> xr IndieFolk albums
Renamed playlist with ID 'PLWptjpDqazOxowHUPbT9Q0AE8F5y2owYm' to 'xr IndieFolk albums'
Renaming: x_r.IndieFolk_tracks_radio --> xr IndieFolk radio
Renamed playlist with ID 'PLWptjpDqazOyxDYgK__A6s3w6B0J7expk' to 'xr IndieFolk radio'
Renaming: x_r.indierock_tracks_like --> xr indierock like
Renamed playlist with ID 'PLWptjpDqazOxj1fnU1gvlpMfqQmsE-WIJ' to 'xr indierock like'
Renaming: x_r.indierock_tracks_radio --> xr indierock radio
Renamed playlist with ID 'PLWptjpDqazOyOe_-mcNny1fvad7pop_bf' to 'xr indierock radio'
Renaming: x_r.Instrumentals_tracks_radio --> xr Instrumentals radio
Renamed playlist with ID 'PLWptjpDqazOyZxlwC7Uw0Sozhf93iArjt' to 'xr Instrumentals radio'
Renaming: x_r.jazz_albums --> xr jazz albums
Renamed playlist with ID 'PLWptjpDqazOxMHAXbWDubZ2HUjKAORBeR' to 'xr jazz albums'
Renaming: x_r.jazz_tracks_radio --> xr jazz radio
Renamed playlist with ID 'PLWptjpDqazOz5HeJ0jPdDFWMQCEqVkFoM' to 'xr jazz radio'
Renaming: x_r.jazznoir_albums --> xr jazznoir albums
Renamed playlist with ID 'PLWptjpDqazOxdndmSn4NknaKVNh9kNB2D' to 'xr jazznoir albums'
Renaming: x_r.jazznoir_tracks_radio --> xr jazznoir radio
Renamed playlist with ID 'PLWptjpDqazOysrTSnxu6OAev1gWJei-dC' to 'xr jazznoir radio'
Renaming: x_r.jazzyhiphop_tracks_radio --> xr jazzyhiphop radio
Renamed playlist with ID 'PLWptjpDqazOwuynXZg_PWH3FG9LjEJPpz' to 'xr jazzyhiphop radio'
Renaming: x_r.krautrock_albums --> xr krautrock albums
Renamed playlist with ID 'PLWptjpDqazOxWPkGDZx3daStgl1fl-UrM' to 'xr krautrock albums'
Renaming: x_r.krautrock_tracks_radio --> xr krautrock radio
Renamed playlist with ID 'PLWptjpDqazOxqubNgZBSsGpo1481TwAo4' to 'xr krautrock radio'
Renaming: x_r.lofihiphop_albums --> xr lofihiphop albums
Renamed playlist with ID 'PLWptjpDqazOySvUxFCwnEBBQWNqO0pc1Q' to 'xr lofihiphop albums'
Renaming: x_r.MelancholyMusic_tracks_like --> xr MelancholyMusic like
Renamed playlist with ID 'PLWptjpDqazOwDJj1xhKgLsNPRiGJaWJBE' to 'xr MelancholyMusic like'
Renaming: x_r.MelancholyMusic_tracks_radio --> xr MelancholyMusic radio
Renamed playlist with ID 'PLWptjpDqazOwa5jy9R_DmkVSFh8zXc2wV' to 'xr MelancholyMusic radio'
Renaming: x_r.melodichouse_tracks_radio --> xr melodichouse radio
Renamed playlist with ID 'PLWptjpDqazOwlN97a5BZQn10nRlLq8CWC' to 'xr melodichouse radio'
Renaming: x_r.minimal_albums --> xr minimal albums
Renamed playlist with ID 'PLWptjpDqazOz8ikzmzCcAzfCC3ZRR4nRZ' to 'xr minimal albums'
Renaming: x_r.minimal_tracks_like --> xr minimal like
Renamed playlist with ID 'PLWptjpDqazOytLIbSTULwLCdADFHtod3X' to 'xr minimal like'
Renaming: x_r.minimal_tracks_radio --> xr minimal radio
Renamed playlist with ID 'PLWptjpDqazOyhP04mbi-UyzJwA1LnYHIh' to 'xr minimal radio'
Renaming: x_r.ModernRockMusic_tracks_radio --> xr ModernRockMusic radio
Renamed playlist with ID 'PLWptjpDqazOxQkoHlCfB_4gwP7alBOiHd' to 'xr ModernRockMusic radio'
Renaming: x_r.MusicToSleepTo_tracks_like --> xr MusicToSleepTo like
Renamed playlist with ID 'PLWptjpDqazOzZ_mjgKyUzCgU6CI9_Jsx3' to 'xr MusicToSleepTo like'
Renaming: x_r.MusicToSleepTo_tracks_radio --> xr MusicToSleepTo radio
Renamed playlist with ID 'PLWptjpDqazOzfumkZJ8sZi_fKVxXLZOfI' to 'xr MusicToSleepTo radio'
Renaming: x_r.NewWave_tracks_radio --> xr NewWave radio
Renamed playlist with ID 'PLWptjpDqazOw4-O-hwyM3sMed2OkZ3GTW' to 'xr NewWave radio'
Renaming: x_r.nudisco_tracks_radio --> xr nudisco radio
Renamed playlist with ID 'PLWptjpDqazOzV0PzMJNYfgF1LiWPSmg65' to 'xr nudisco radio'
Renaming: x_r.OldiesMusic_tracks_radio --> xr OldiesMusic radio
Renamed playlist with ID 'PLWptjpDqazOwPPKh7f_CBG7AwMk0t6-q4' to 'xr OldiesMusic radio'
Renaming: x_r.OldskoolRave_tracks_like --> xr OldskoolRave like
Renamed playlist with ID 'PLWptjpDqazOxzQDP8Dp_eshO5-a3InZsN' to 'xr OldskoolRave like'
Renaming: x_r.OldskoolRave_tracks_radio --> xr OldskoolRave radio
Renamed playlist with ID 'PLWptjpDqazOzdzSlv3kyD0FNYfEqMC7Ct' to 'xr OldskoolRave radio'
Renaming: x_r.OutlawCountry_tracks_radio --> xr OutlawCountry radio
Renamed playlist with ID 'PLWptjpDqazOyH6tejSSllauZTKxTAiAwC' to 'xr OutlawCountry radio'
Renaming: x_r.PostRock_albums --> xr PostRock albums
Renamed playlist with ID 'PLWptjpDqazOzcQ1BO8fqTlSZM1SVElySE' to 'xr PostRock albums'
Renaming: x_r.PostRock_tracks_radio --> xr PostRock radio
Renamed playlist with ID 'PLWptjpDqazOwNpWr_ISIR4lAotyqYBAo7' to 'xr PostRock radio'
Renaming: x_r.psychedelicrock_albums --> xr psychedelicrock albums
Renamed playlist with ID 'PLWptjpDqazOzZ1fNE1koysy9fG0Z4jJaI' to 'xr psychedelicrock albums'
Renaming: x_r.PsychedelicRock_tracks_like --> xr PsychedelicRock like
Renamed playlist with ID 'PLWptjpDqazOyYRm_y1gmgiQvhzMWIiN3t' to 'xr PsychedelicRock like'
Renaming: x_r.PunkRock_albums --> xr PunkRock albums
Renamed playlist with ID 'PLWptjpDqazOyJ04Dg7Se1V-RMBc8VauzZ' to 'xr PunkRock albums'
Renaming: x_r.PunkRock_tracks_like --> xr PunkRock like
Renamed playlist with ID 'PLWptjpDqazOyD8EdMeeTWlF2EkssJinl0' to 'xr PunkRock like'
Renaming: x_r.PunkRock_tracks_radio --> xr PunkRock radio
Renamed playlist with ID 'PLWptjpDqazOxddnjiYJuy7sQLOwZntMTr' to 'xr PunkRock radio'
Renaming: x_r.rainymood_albums --> xr rainymood albums
Renamed playlist with ID 'PLWptjpDqazOyFdcc2XFSJYCYcznypdOHt' to 'xr rainymood albums'
Renaming: x_r.rainymood_tracks_like --> xr rainymood like
Renamed playlist with ID 'PLWptjpDqazOwV1QjufzELY_X5xmIxlmP4' to 'xr rainymood like'
Renaming: x_r.rainymood_tracks_radio --> xr rainymood radio
Renamed playlist with ID 'PLWptjpDqazOzyqnJ3vyaqGgi8oPPBgIar' to 'xr rainymood radio'
Renaming: x_r.realdubstep_tracks_like --> xr realdubstep like
Renamed playlist with ID 'PLWptjpDqazOxLvllR3H1_7d3ENvCpv_bz' to 'xr realdubstep like'
Renaming: x_r.realdubstep_tracks_radio --> xr realdubstep radio
Renamed playlist with ID 'PLWptjpDqazOwMf4gPALXALzg4GpPrYQWk' to 'xr realdubstep radio'
Renaming: x_r.reggae_albums --> xr reggae albums
Renamed playlist with ID 'PLWptjpDqazOwKncLcrXesGez2ehO0qM0I' to 'xr reggae albums'
Renaming: x_r.reggae_tracks_radio --> xr reggae radio
Renamed playlist with ID 'PLWptjpDqazOyYxdvXyzAD5z01_Kv7c7mx' to 'xr reggae radio'
Renaming: x_r.Rock_tracks_like --> xr Rock like
Renamed playlist with ID 'PLWptjpDqazOwNTc9f3s_J5m0T68-g5eVl' to 'xr Rock like'
Renaming: x_r.shoegaze_albums --> xr shoegaze albums
Renamed playlist with ID 'PLWptjpDqazOxJ3HxhoEgP8sLSVC3p0x5g' to 'xr shoegaze albums'
Renaming: x_r.SoundsVintage_albums --> xr SoundsVintage albums

### Generate playlist for need like from musicbee

In [4]:
uni_module_path = os.path.abspath(os.path.join('../../music-sources-unified'))
if uni_module_path not in sys.path: sys.path.append(uni_module_path)
import pandas as pd

DRY_RUN = False
VERBOSE = True
MAX_PL_TRACKS = 4000
PLAYLIST_NAME = 'zz need like'

# This will like them all, need to manually look at result and unlike live or remixes falsly matched
MB_YT_LIKE = os.path.join(uni_module_path, 'tsvs', 'ytmusic_tracks_to_like_from_mb_album_matches.tsv')
mb_yt_like = pd.read_csv(MB_YT_LIKE, sep='\t')
track_ids = mb_yt_like['yt_videoId'].dropna().unique().tolist()
desc = f'{PLAYLIST_NAME} with {len(track_ids)} tracks that are >3.5 in musicbee'
print(f'Accumulated {len(track_ids)} track ids')
if not DRY_RUN:
  print('manually check these, most are false positives, some need like')
  pl_id = Y.yt.create_playlist(
                    title=PLAYLIST_NAME, description='',
                    privacy_status='PRIVATE', video_ids=list(track_ids)
                )
  # pl_id = Y.playlist_from_yt_vids(track_ids, pl_name=PLAYLIST_NAME, sleep=0.5, public='PRIVATE', desc=desc,
  #                         dry=DRY_RUN, set_rating=None, remove_dupes=False, verbose=VERBOSE)
  print(f'Generated playlist: {PLAYLIST_NAME} with id {pl_id}')
  
## TODO 400 err, meant to use for >4000 track max
# if not DRY_RUN:
#   for i in range((len(track_ids) + MAX_PL_TRACKS - 1) // MAX_PL_TRACKS):
#       # chunk_name = f"{PLAYLIST_NAME} {i+1}" if len(track_ids) > MAX_PL_TRACKS else PLAYLIST_NAME
#       vids = track_ids[i*MAX_PL_TRACKS:(i+1)*MAX_PL_TRACKS]
#       pl_id = Y.playlist_from_yt_vids(vids, pl_name=chunk_name, sleep=0.5, public='PRIVATE', desc=desc,
#                               dry=DRY_RUN, set_rating=None, remove_dupes=False, verbose=VERBOSE)
#       print(f'Generated playlist: {chunk_name} with id {pl_id}')

Accumulated 1533 track ids
manually check these, most are false positives, some need like
Generated playlist: zz need like with id PLWptjpDqazOzc8sZVQpg4YBmWKc2uX1J1

## Like all tracks in playlist

Note good to manually check first

In [ ]:
# Initialize the YTMusicPlaylists object

# 1. Find the specific playlist
target_playlist_name = "zz need like"
playlist_row = Y.query_by_title(target_playlist_name)
# 2. Get the full playlist info (including the track list)
pl_info = Y.playlist_get_info(playlist_row['playlistId'], use_cache=False)
# 3. Rate all songs in the playlist as 'LIKE'
results = Y.playlist_rate_all_songs(pl_info, rating='LIKE', verbose=False)
print(f"\nFinished! Results for '{target_playlist_name}':")

### Generate playlist froma a list of albums

In [ ]:
# ORIG
# name = 'y_2023_albums_to_listen_to_v3'
# desc = 'manually selected albums to top off 2023 albums'
# albums_to_add = [
# "Aesop Rock - Integrated Tech Solutions",
# "Mitski - The Land Is Inhospitable and So Are We",
# "Olivia Rodrigo - GUTS",
# "The National - First Two Pages Of Frankenstein",
# "Foo Fighters - But Here We Are",
# "Jessie Ware - That! Feels Good!",
# ]


# TODO run this before playlistbackup
# Playlist for all mb library albums
dry_run = False
verbose = False
uni_module_path = os.path.abspath(os.path.join('../../music-sources-unified'))
if uni_module_path not in sys.path: sys.path.append(uni_module_path)
import unify_lib as uni
import pandas as pd
import time

YT_ALBUM_MATCH_TSV = os.path.join(uni_module_path, 'tsvs', 'ytmusic_musicbee_album_matches.tsv')

DATE = time.strftime('%m-%d-%Y')
MAX_PL_TRACKS = 4000

# Just do library
MB_LIB = os.path.join(uni_module_path, 'db_assets', 'musicbee_library.tsv')

# MB_INBOX = os.path.join(uni_module_path, 'db_assets', 'musicbee_inbox.tsv')
name = 'za mb library unmatched albums v2'
desc = f' albums in mb library but not not in ytmusic_musicbee_album_matches.tsv {DATE}'


print('Loading ytmusic and musicbee library track databases (takes ~1m)')
# mb_tracks = uni.ingest_musicbee_db_assets(MB_LIB, MB_INBOX)
mb_tracks = pd.read_csv(MB_LIB, sep='\t')
mb_tracks['fuzzy_album_id'] = mb_tracks.apply(uni.make_mb_fuzzy_album_id, axis=1)
albums_to_add = frozenset(mb_tracks['fuzzy_album_id'].unique())
initial_num_albums = len(albums_to_add)  # Calculate BEFORE removing any albums

last_album_matches = pd.read_csv(YT_ALBUM_MATCH_TSV, sep='\t', index_col=0, low_memory=False)
last_album_matches = last_album_matches.loc[last_album_matches['mb_match_label'] == 'MATCH']
last_album_matches = frozenset(last_album_matches['mb_match'].unique())

albums_removed = albums_to_add.intersection(last_album_matches)
num_removed = len(albums_removed)
albums_to_add -= last_album_matches 
print(f'Loaded {initial_num_albums} unique musicbee albums')
print(f'Loaded {len(last_album_matches)} unique previous matched mb albums already in yt library')
print(f"Removed {num_removed} albums ({(num_removed / initial_num_albums):.0%}) already in last_album_matches.")
print(f'Attempting to add {len(albums_to_add)} albums to ytmusic playlist')

track_ids = []
skipped = set()
for i, a in enumerate(albums_to_add):
    if a in skipped: continue
    res = Y.yt.search(query=a, filter='albums', limit=1)
    if len(res) == 0 or res[0].get('browseId') == None:
        a2 = a.split(' [')[0].split(' (')[0]
        res = Y.yt.search(query=a2, filter='albums', limit=1)
        if len(res) == 0 or res[0].get('browseId') == None:
          if verbose:
            print(f'Skipping query: {a} empty album match result: {res}')
          skipped.add(a)
          continue
    result_album = f"{res[0]['artists'][0]['name']} - {res[0]['title']}"
    yt_album = Y.yt.get_album(res[0]['browseId'])
    for t in yt_album['tracks']:
        t_vid = t['videoId'] 
        # if t_vid not in added_vids:
        track_ids.append(t_vid)
          # print('+', end='')
    if verbose:
      print(f'({i+1}) Added {len(yt_album["tracks"])} tracks":\tq: {a}\tr: {result_album.lower()}')
    if i % 100 == 0:
      print(int(100*i/len(albums_to_add)), end='%...\n')

print(f'Accumulated {len(track_ids)} track ids')

if not dry_run:
  for i in range((len(track_ids) + MAX_PL_TRACKS - 1) // MAX_PL_TRACKS):
      chunk_name = f"{name} {i+1}" if len(track_ids) > MAX_PL_TRACKS else name
      vids = track_ids[i*MAX_PL_TRACKS:(i+1)*MAX_PL_TRACKS]
      pl_id = Y.playlist_from_yt_vids(vids, pl_name=chunk_name, sleep=0.5, public='PRIVATE', desc=desc,
                              dry=dry_run, set_rating=None, remove_dupes=False, verbose=False)
      
      print(f'Generated playlist: {chunk_name} with id {pl_id}')

Loading ytmusic and musicbee library track databases (takes ~1m)

C:\Users\jake\AppData\Local\Temp\ipykernel_13480\1568832776.py:39: DtypeWarning: Columns (7,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  mb_tracks = pd.read_csv(MB_LIB, sep='\t')

Loaded 5532 unique musicbee albums
Loaded 4962 unique previous matched mb albums already in yt library
Removed 4228 albums (76%) already in last_album_matches.
Attempting to add 1304 albums to ytmusic playlist
0%...
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++7%...
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++15%...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++30%...
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++53%...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++61%...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++69%...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++76%...
+++++++++++++++++++++++++++++++++++++++++++++84%...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++92%...
++++++++++++++++++99%...
Accumulated 892 track ids

Generating za mb library unmatched albums v2 ytmusic playlist for 892 tracks
Saved za mb library unmatched albums v2 playlist with 892 tracks and playlist id: PLWptjpDqazOxmAid1e5lMncW86hEBG42G, waiting 0.5 seconds...
Generated playlist: za mb library unmatched albums v2 with id PLWptjpDqazOxmAid1e5lMncW86hEBG42G

In [22]:
len(added_vids)

14081

### Publicize Like Playlists

In [26]:
# Get possible tracks to add to radio like playlist map
import pandas as pd
from pprint import pprint
import time

DATE = time.strftime('%m-%d-%Y')

like_playlists = frozenset(pd.read_csv('..\\playlists\\_like_playlists.tsv', sep='\t')['title'])
radio_map = pd.read_csv('..\\playlists\\_ytmusic_radio_to_like_pl_map.tsv', sep='\t')
like_playlists_mapped = frozenset(radio_map['like_playlist'])
# radio_map = dict(zip(radio_map['radio_playlist'], radio_map['like_playlist']))

#### Run regularly to update privacy to public

maxes if if too many set to public in one day

In [27]:
dry_run = False
print_warn = False
set_public = True # maxes out quickly
min_count_for_public = 15
finished = []
for i, pl in Y.playlists.iterrows():
  p = pl['title']
  if p not in like_playlists:
    if 'like' in p and  not 'not like' in p:
      print('Skipping not in like_playlist:', p)
    continue
    
  if p not in like_playlists_mapped:
    if print_warn: print('Warning not in like_playlist_mapped:', p)
    pass
  
      
  # tmp reset desc
  desc=None
  if p.startswith('xr '):
    desc = f"favorites compiled from reddit sub r/{p.replace('xr ', '')}".strip()
       
  # set to public if not set and enough tracks
  privacy = None
  if set_public:
    privacy = 'PUBLIC'
    count = int(str(pl['count']).replace(',', ''))
    if count < min_count_for_public:
      print(f'Keeping private too small: {pl["count"]} < {min_count_for_public}:', p)
      privacy = None
    
    metadata = Y.playlist_get_info(pl["playlistId"])
    if metadata['privacy'] == privacy:
      print('Already public:', p)
      privacy = None

  # Apply
  if dry_run:
    print(f"Y.yt.edit_playlist(playlistId={pl['playlistId']}, privacyStatus={privacy}, description={desc})")
  else:
    status = Y.yt.edit_playlist(playlistId=pl['playlistId'],  privacyStatus=privacy, description=desc)
    print(f"Updated {p} with status={status}, privacy={privacy}, description={desc}")
    finished.append(p)

Already public: future beats
Updated future beats with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: reggae classic
Updated reggae classic with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: Reggae
Updated Reggae with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic jaar
Updated electronic jaar with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated rock classic with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Already public: rock 1970s classic
Updated rock 1970s classic with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated xr chillmusic with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=favorites compiled from reddit sub r/chillmusic
Already public: jazz blue note
Updated jazz blue note with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: reggae covers
Updated reggae covers with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: jazz guitar
Updated jazz guitar with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated Shoegaze with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Already public: indie folk
Updated indie folk with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated indie with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Already public: rock stoner sludge dank
Updated rock stoner sludge dank with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated ambient with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Already public: jazz noir
Updated jazz noir with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: jazz
Updated jazz with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: xr house
Updated xr house with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/house
Already public: hiphop
Updated hiphop with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated future bass with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Already public: xr bassheavy
Updated xr bassheavy with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/bassheavy
Already public: electronic 2000s
Updated electronic 2000s with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: xr PunkRock
Updated xr PunkRock with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/PunkRock
Updated xr 2000smusic with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=favorites compiled from reddit sub r/2000smusic
Updated soul funk with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Updated rock garage with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Already public: rock 1990s
Updated rock 1990s with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated rock 1990s alternative with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Already public: post rock slow core
Updated post rock slow core with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated future garage with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Already public: electronic Garage Bass House
Updated electronic Garage Bass House with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated electronic Focus with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Updated ambient modern with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Updated Rock 1980s Pop New Wave with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Updated Post-Punk 1970s-1980s with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Updated Hip Hop 1990s west Coast with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Already public: Hip Hop 1990s
Updated Hip Hop 1990s with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: Folk
Updated Folk with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated xr hiphop with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=favorites compiled from reddit sub r/hiphop
Already public: soul motown
Updated soul motown with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated garage rock with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Already public: xr 60sMusic
Updated xr 60sMusic with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/60sMusic
Already public: electronic witch house
Updated electronic witch house with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: xr VintageObscura
Updated xr VintageObscura with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/VintageObscura
Already public: xr SoundsVintage
Updated xr SoundsVintage with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/SoundsVintage
Updated xr RootsMusic with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=favorites compiled from reddit sub r/RootsMusic
Already public: xr Rock
Updated xr Rock with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/Rock
Updated xr PsychedelicRock with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=favorites compiled from reddit sub r/PsychedelicRock
Updated xr OutlawCountry with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=favorites compiled from reddit sub r/OutlawCountry
Already public: rock krautrock
Updated rock krautrock with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: xr idm
Updated xr idm with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/idm
Already public: jazz gypsy
Updated jazz gypsy with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: xr Elephant6
Updated xr Elephant6 with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/Elephant6
Already public: xr disco
Updated xr disco with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/disco
Already public: xr deepcuts
Updated xr deepcuts with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/deepcuts
Already public: xr dancepunk
Updated xr dancepunk with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/dancepunk
Updated xr 70sMusic with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=favorites compiled from reddit sub r/70sMusic
Already public: xr bluesrock
Updated xr bluesrock with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/bluesrock
Already public: blues
Updated blues with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: xr bluegrass
Updated xr bluegrass with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/bluegrass
Updated xr altcountry with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=favorites compiled from reddit sub r/altcountry
Updated xr acidhouse with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=favorites compiled from reddit sub r/acidhouse
Already public: xr 90sRock
Updated xr 90sRock with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/90sRock
Already public: xr 50sMusic
Updated xr 50sMusic with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/50sMusic
Updated rock surf with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Already public: electronic dubstep uk
Updated electronic dubstep uk with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated xr treemusic with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=favorites compiled from reddit sub r/treemusic
Already public: electronic Underjord
Updated electronic Underjord with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated xr neopsychedelia with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=favorites compiled from reddit sub r/neopsychedelia
Updated xr Exotica with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=favorites compiled from reddit sub r/Exotica
Already public: electronic Innerwaves
Updated electronic Innerwaves with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic
Updated electronic with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic chill
Updated electronic chill with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated xr chillwave with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=favorites compiled from reddit sub r/chillwave
Already public: electronic New Wave old and new
Updated electronic New Wave old and new with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: nudisco
Updated nudisco with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: indie loose
Updated indie loose with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: chill solar mix
Updated chill solar mix with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated indie sleeze with status=STATUS_FAILED, privacy=PUBLIC, description=None
Already public: helvetia duster static cult
Updated helvetia duster static cult with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated xr monsterfuzz with status=STATUS_FAILED, privacy=PUBLIC, description=favorites compiled from reddit sub r/monsterfuzz
Already public: Hip Hop Hits
Updated Hip Hop Hits with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: hiphop modern
Updated hiphop modern with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic Sine Language
Updated electronic Sine Language with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: hiphop old school
Updated hiphop old school with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: xr 2010smusic
Updated xr 2010smusic with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/2010smusic
Already public: xr 80sMusic
Updated xr 80sMusic with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/80sMusic
Updated xr DreamPop with status=STATUS_FAILED, privacy=PUBLIC, description=favorites compiled from reddit sub r/DreamPop
Already public: xr theOverload
Updated xr theOverload with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/theOverload
Already public: xr minimal
Updated xr minimal with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/minimal
Updated Instrumentals Acoustic with status=STATUS_FAILED, privacy=PUBLIC, description=None
Already public: xr realdubstep
Updated xr realdubstep with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/realdubstep
Already public: blues deep roots
Updated blues deep roots with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: xr futurefunkairlines
Updated xr futurefunkairlines with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/futurefunkairlines
Already public: psych rock modern
Updated psych rock modern with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated jazz fusion cross with status=STATUS_FAILED, privacy=PUBLIC, description=None
Already public: soul instrumental grooves
Updated soul instrumental grooves with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: jazz funk cortex vibe
Updated jazz funk cortex vibe with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: Reggae Dub
Updated Reggae Dub with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: Bossa Nova
Updated Bossa Nova with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: xr trapmuzik
Updated xr trapmuzik with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/trapmuzik
Already public: hiphop jazzy
Updated hiphop jazzy with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: xr futuresynth
Updated xr futuresynth with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/futuresynth
Updated xr ModernRockMusic with status=STATUS_FAILED, privacy=PUBLIC, description=favorites compiled from reddit sub r/ModernRockMusic
Already public: xr MelancholyMusic
Updated xr MelancholyMusic with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/MelancholyMusic
Already public: oldies fallout 40s
Updated oldies fallout 40s with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: brass beats
Updated brass beats with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: ambient grouper
Updated ambient grouper with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: ambient japan
Updated ambient japan with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: rockabilly
Updated rockabilly with status=STATUS_SUCCEEDED, privacy=None, description=None
Updated rock 60s70s with status=STATUS_SUCCEEDED, privacy=PUBLIC, description=None
Already public: Oldies
Updated Oldies with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: trip hop
Updated trip hop with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: blues electric
Updated blues electric with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: jazz spiritual
Updated jazz spiritual with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic big beats
Updated electronic big beats with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: folk country americana
Updated folk country americana with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: xr 90sPunk
Updated xr 90sPunk with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/90sPunk
Already public: electronic house funk
Updated electronic house funk with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: rock underground
Updated rock underground with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: beats
Updated beats with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: beats instrumental
Updated beats instrumental with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic new indie beats
Updated electronic new indie beats with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: Grunge
Updated Grunge with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: Indie psych
Updated Indie psych with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: oldies 1960s
Updated oldies 1960s with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: trip hop & Ambien®
Updated trip hop & Ambien® with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: hiphop wrist twistin
Updated hiphop wrist twistin with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: oldies doo wop
Updated oldies doo wop with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: oldies 1950s
Updated oldies 1950s with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic 1990s electronica
Updated electronic 1990s electronica with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: ambient modular synths
Updated ambient modular synths with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: psych ish rock modern
Updated psych ish rock modern with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: beats dj
Updated beats dj with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: indie krill vibe
Updated indie krill vibe with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: hiphop soul good vibe
Updated hiphop soul good vibe with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic deep house
Updated electronic deep house with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: rock 1950s roots
Updated rock 1950s roots with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: xr 90sMusic
Updated xr 90sMusic with status=STATUS_SUCCEEDED, privacy=None, description=favorites compiled from reddit sub r/90sMusic
Already public: electronic chills adventure
Updated electronic chills adventure with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic house french touch
Updated electronic house french touch with status=STATUS_SUCCEEDED, privacy=None, description=None
Keeping private too small: 11 < 15: Japanese City Pop 70s 80s
Updated Japanese City Pop 70s 80s with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic Dance
Updated electronic Dance with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: jazz sunrise
Updated jazz sunrise with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: Beats Lofi
Updated Beats Lofi with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic 1990s late 1980s House
Updated electronic 1990s late 1980s House with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic house
Updated electronic house with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: hiphop Soulquarians
Updated hiphop Soulquarians with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: jazz japanese
Updated jazz japanese with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic House Soulful
Updated electronic House Soulful with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: triphop bristol sound
Updated triphop bristol sound with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic House Special
Updated electronic House Special with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic post dub
Updated electronic post dub with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: electronic uk
Updated electronic uk with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: soul kings and queens
Updated soul kings and queens with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: soul 1960s
Updated soul 1960s with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: oldies 1930-40s naptime
Updated oldies 1930-40s naptime with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: synth trip
Updated synth trip with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: jazz blue note latin
Updated jazz blue note latin with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: rock 1960s classic
Updated rock 1960s classic with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: jazz ballads
Updated jazz ballads with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: jazz cool
Updated jazz cool with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: Hip Hop 1990s east coast
Updated Hip Hop 1990s east coast with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: beats 2010s wonky LA scene
Updated beats 2010s wonky LA scene with status=STATUS_SUCCEEDED, privacy=None, description=None
Already public: jazz gloom smooth

#### (one time) check like playlists, make sure valid

In [ ]:
# dry_run = False
# log_playlist = False
# reset_description = True
# finished = []

# for i, pl in Y.playlists.iterrows():
#   p = pl['title']

#   # Filter 'valid' to like playlist
#   if p in finished:
#     print('Skip already finished:', p)
#     continue
#   if 'not like' in p:
#     # print('Skip:', p)
#     continue
#   if  '_like' in p:
#     print('Skip playlist has "_like":', p)
#     continue
#   if ' like' not in p:
#     continue
#   elif not p.endswith('like'):
#     print('Weird case not end with like:', p)
#     continue
#   if p not in like_playlists:
#     # print(p) # update _like_playlist.tsv
#     print('Skip Not logged as _like_playlist:', p)
#     continue
#   elif p not in like_playlists_mapped:
#     # print(f'{p.replace("like", "radio")}\t{p}') # update radio_to_like_pl_map
#     print('Skip Not logged as radio to like map:', p)
#     continue
#   if len(pl['playlistId']) != 34:
#     print('Skip invalid playlisdId', pl['playlistId'], p)
    
    
#   assert p.endswith(' like')
#   new_p = p.replace(' like', '')
#   if log_playlist:
#     p_dict = pl.to_dict()
#     p_dict.pop('thumbnails')
#     pprint(p_dict, sort_dicts=False)

#   # if not p.startswith('xr'): print(p)
#   desc = None
#   if reset_description:
#     # print('Reset Description for:', p, desc)
#     desc = 'favorites'
#     if p.startswith('xr '):
#       desc += f" compiled from reddit sub r/{p.replace(' xr', '')}"
    
  
#   if dry_run:
#     print(f"Y.yt.edit_playlist(playlistId={pl['playlistId']}, title={new_p}, description={desc})")
#   else:
#     status = Y.yt.edit_playlist(playlistId=pl['playlistId'], title=new_p, description=desc)
#     print(f"Updated {p} with status={status}, reset_description={reset_description}")
#     finished.append(p)

Skip already finished: xr PunkRock like
Skip already finished: xr 90sPunk like
Skip already finished: ambient grouper like
Skip already finished: folk country americana like
Skip already finished: rock underground like
Skip already finished: xr deepcuts like
Skip already finished: trip hop & Ambien® like
Skip already finished: xr trapmuzik like
Skip already finished: oldies fallout 40s like
Skip already finished: xr 90sRock like
Skip already finished: xr SoundsVintage like
Skip already finished: xr chillmusic like
Skip already finished: xr OutlawCountry like
Skip already finished: psych ish rock modern like
Skip already finished: rock garage like
Skip already finished: xr treemusic like
Skip already finished: brass like
Skip already finished: xr 70sMusic like
Skip already finished: xr 90sMusic like
Skip already finished: xr DreamPop like
Skip already finished: xr theOverload like
Skip already finished: xr PsychedelicRock like
Skip already finished: xr Rock like
Skip already finished: ambient modern like
Skip already finished: xr idm like
Skip already finished: xr Elephant6 like
Skip already finished: electronic Underjord like
Updated electronic chills adventure like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr futurefunkairlines like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr futuregarage like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr futurebeats like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr 2000smusic like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated Japanese City Pop 70s 80s like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated electronic Sine Language like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr chillwave like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr house like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xs Solar Chillout like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated electronic Garage Bass House like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated soul instrumental grooves like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated electronic post dub like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr WorldMusic like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr disco like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated soul kings and queens like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xs hiphop modern like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated electronic New Wave old and new like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr dancepunk like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated synth trip like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated electronic film scores like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr 50sMusic like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr 60sMusic like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated Instrumentals Acoustic like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr VintageObscura like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr SurfPunk like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr stonerrock like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr realdubstep like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr rainymood like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr OldskoolRave like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr MusicToSleepTo like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr minimal like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr MelancholyMusic like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr indierock like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr HeadNodders like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr futuresynth like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr bluesrock like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr bluegrass like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr bassheavy like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr 90sAlternative like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr 80sMusic like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr 80sHipHop like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr 2010smusic like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr synthrock like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None
Updated xr AfricanMusic like with status=STATUS_SUCCEEDED, reset_description=True, privacy=None